// Generated by company-of-heroes-assets/tools/extract_action_info.py from the CoH1
// attrib archive and the English UCS locale. Do not edit by hand.

import type { ActionInfo } from './replay-action-info';

/** In-game name, help text and "good vs." line per blueprint list -> objectID. */
export const ACTION_INFO: Record<string, Record<number, ActionInfo>> = {
	abilities: {
		1: { name: 'Field Repairs', help: 'Crews will Repair their own Vehicles automatically.' },
		2: {
			name: 'Armor Piercing Shells',
			help: 'Fires high penetration Armor Piercing Shells for a short duration.',
			extra: 'Good vs. Tanks'
		},
		3: {
			name: 'Armor Piercing Burst',
			help: 'M2 Armor Piercing (AP) ball ammunition is loaded into the Machine Gun, making it very effective against Light Vehicles. HMG must be set up and able to fire at the target for the rounds to work.',
			extra: 'Good vs. Light Vehicles'
		},
		4: {
			name: 'Fire Recoilless Rifle',
			help: 'Fire the Recoilless Rifle at Enemy Armor or Structures.',
			extra: 'Good vs. Tanks and Vehicles'
		},
		5: {
			name: 'Air Reconnaissance',
			help: 'A P-47 recon overflight reveals an area of the map and all Units within that area.'
		},
		7: {
			name: 'Bombing Run',
			help: 'A P-47 Thunderbolt will drop a line of Bombs on Enemy targets.',
			extra: 'Good vs. Vehicles'
		},
		8: {
			name: 'Strafing Run',
			help: 'A P-47 Thunderbolt will strafe targets with its eight .50 cal Machine Guns.',
			extra: 'Good vs. Infantry'
		},
		10: {
			name: 'Calliope Barrage',
			help: 'Ripple fire a massive Rocket Barrage from the T34 Launcher on the Calliope.',
			extra: 'Area of Effect. Good vs. Infantry and Light Vehicles.'
		},
		11: {
			name: 'Fire-Up',
			help: 'While Fired-Up, Squads are less prone to Suppression and move faster for a short time. After the effects of Fire-Up wear off, the squad will suffer from exhaustion, reducing their movement and attack speeds for a short period.'
		},
		14: {
			name: 'Lower/Raise the Bulldozer',
			help: 'Lowers the Bulldozer attachment. When engaged the Tank can clear hedgerows, Tank Traps, and other heavy obstacles.'
		},
		15: {
			name: '105mm Howitzer Barrage',
			help: 'Long range Howitzers will fire a Barrage of rounds at specified targets. Can be fired into the Fog of War.',
			extra: 'Area of Effect attack. Good vs. Infantry and Light Vehicles'
		},
		17: {
			name: 'Smoke Barrage',
			help: 'Smoke Shells will be fired into the area ordered to provide cover for nearby Soldiers or Vehicles.',
			extra: 'Good Cover'
		},
		22: {
			name: 'Howitzer Shoot',
			help: 'Call in Artillery Strike on designated target area.',
			extra: 'Area of Effect attack. Good vs. Infantry and Light Vehicles'
		},
		23: {
			name: 'Airdrop M1 57mm Anti Tank Gun',
			help: 'Support Airborne landings with an Airdropped Anti Tank gun for extra firepower against Vehicles and Buildings.',
			extra: 'Good vs. Vehicles and Structures'
		},
		24: {
			name: 'Airborne Infantry',
			help: 'A Squad of well-armed and highly-trained Paratroopers will paradrop onto the ordered location.',
			extra: 'Versatile Squad with Satchel Charges and Recoilless Rifle upgrade'
		},
		30: {
			name: 'Supply Drops',
			help: 'Paradrop Munitions, Fuel Supplies, and some heavy weapons to Revealed Territory.'
		},
		35: {
			name: 'Call In Rangers',
			help: 'Call in a Squad of Rangers.',
			extra: 'Good vs. Tanks and Infantry'
		},
		37: {
			name: 'Suppression Fire',
			help: 'Suppression Fire can pin Enemy Troops except when the target is in heavy cover',
			extra: 'Good vs. Infantry'
		},
		38: {
			name: '60mm Mortar Bombardment',
			help: 'Saturate area with 60mm Mortar rounds.',
			extra: 'Good vs. Infantry'
		},
		40: {
			name: 'Throw Grenade',
			help: "The Squad will throw a Mk2 'Pineapple' Grenade.",
			extra: 'Good vs. Infantry, Infantry in Cover'
		},
		43: {
			name: 'Throw Satchel Charge',
			help: 'Satchel Charges are bundles of explosives that do heavy damage against Buildings, but can be thrown at Vehicles or Infantry.',
			extra: 'Good vs. Buildings, Infantry'
		},
		45: {
			name: 'Throw Sticky Bomb',
			help: 'Sticky Bombs are improvized Anti Tank weapons.',
			extra: 'Good vs. Vehicles and Tanks'
		},
		50: {
			name: 'PIAT Ambush',
			help: "PIAT Ambush will enable PIAT armed Sappers to enter camouflage when using cover. They'll be able to fire several shots before being detected."
		},
		52: {
			name: 'Allied War Machine',
			help: 'Replaces up to 2 destroyed Allied tanks with a new Tank for a period of time.'
		},
		53: {
			name: 'Observed Fire',
			help: 'A tight cluster of 81mm Mortar rounds will fall accurately on the chosen target area.',
			extra: 'Good vs. Infantry, Light Vehicles'
		},
		54: {
			name: '280mm Rocket Barrage',
			help: 'Call in a 280mm Rocket Barrage.',
			extra: 'Area of Effect attack. Good vs. Infantry and Light Vehicles'
		},
		55: {
			name: 'Assault',
			help: 'The Squad will unleash a vicious rain of Grenades before getting into close range with the target.',
			extra: 'Good vs. Infantry, Light Buildings'
		},
		56: {
			name: 'Camouflage',
			help: 'Camouflage conceals the Pak 38 giving it a First Strike ambush bonus against Enemy Units.'
		},
		57: {
			name: 'Fire Panzerfaust',
			help: 'Fire the disposable 100mm Panzerfaust at Enemy Armor or Structures.',
			extra: 'Good vs. Tanks and Vehicles'
		},
		58: {
			name: 'Fire Panzerfaust',
			help: 'Fire the disposable 100mm Panzerfaust at Enemy Armor or Structures.',
			extra: 'Good vs. Tanks and Vehicles'
		},
		60: {
			name: 'Inspired Assault',
			help: 'All infantry will unleash a fearsome assault for the Leader at the cost of their safety, increases rate of fire and damage, but more susceptible to being hit.'
		},
		63: {
			name: 'Assault',
			help: 'The Squad will unleash a vicious rain of Grenades before getting into close range with the target.',
			extra: 'Good vs. Infantry, Light Buildings'
		},
		64: {
			name: 'Manpower Blitz',
			help: 'HQ awards you with 900 Manpower for outstanding bravery, Manpower rate is reduced to 50% for 3 minutes after triggering this ability.'
		},
		65: {
			name: 'Smoke Barrage',
			help: 'Smoke Shells will be fired into the area ordered to provide cover for nearby Soldiers or Vehicles.',
			extra: 'Good Cover'
		},
		66: {
			name: 'Nebelwerfer Barrage',
			help: 'Barrage an area with six 150mm incendiary Nebelwerfer rockets that can cause burn damage to infantry and structures.',
			extra: 'Area of Effect attack. Good vs. Infantry and Light Vehicles'
		},
		69: {
			name: 'Registered Artillery',
			help: 'Registered artillery can call in a defensive bombardment on any player or team-owned building or point.',
			extra: 'Good vs. Infantry, Light Vehicles'
		},
		70: {
			name: 'Air-Dropped SD-2 Butterfly Bombs',
			help: 'Butterfly Bombs are dropped from the air and blanket the selected area. The Butterfly Bombs are a capable anti-personnel mine.',
			extra: 'Good vs. Infantry'
		},
		73: {
			name: 'Rapid Fire Shells',
			help: 'Crew will fire shells at a rapid rate for a short duration.',
			extra: 'Good vs. Tanks'
		},
		74: {
			name: 'King Tiger',
			help: "Call in a rare King Tiger, a veritable mobile fortress of a tank. The King Tiger is only available once per game, once you lose it, it's gone.",
			extra: 'Good vs. Tanks'
		},
		76: {
			name: 'Infantry Assault Team',
			help: 'Call in a Squad of Stormtroopers for Reinforcement.'
		},
		77: { name: 'Urban Assault Support', help: 'Call in a StuH 42 Assault Gun.' },
		78: { name: 'Armored Assault Force', help: 'Call in a Tiger heavy tank.' },
		79: {
			name: 'Rocket Barrage',
			help: 'Barrage the area ordered with six Wurfrahmen 40" Heavy Rockets',
			extra: 'Area of Effect attack. Good vs. Light Vehicles and Buildings'
		},
		80: {
			name: '81mm Mortar Bombardment',
			help: 'Several high-angle 81mm Mortar Rounds will be fired into the targeted area.',
			extra: 'Good vs. Infantry'
		},
		84: {
			name: 'Firestorm',
			help: 'Call Off-Map Bombardment to target area. All Enemy Troops will be caught in a Firestorm.',
			extra: 'Area of Effect attack. Good vs. Infantry and Light Vehicles'
		},
		85: {
			name: 'Throw Grenade',
			help: 'The Squad will throw a Model 24 Stielgranate.',
			extra: 'Good vs. Infantry, Infantry in Cover'
		},
		87: {
			name: 'Throw Bundled Grenade',
			help: 'Six Grenade heads bundled around a single handle deliver a powerful blast.',
			extra: 'Good vs. Infantry, Infantry in Cover'
		},
		90: {
			name: 'Blitzkrieg',
			help: 'All Tanks and Armored Vehicles move more quickly, crush everything in their path, and fire more frequently. Infantry sprint to keep pace.',
			extra: 'BLITZKRIEG!!!'
		},
		91: {
			name: 'Booby Traps',
			help: 'Wire strategic points and ambient buildings to explode when enemies begin capturing point, or enter building.'
		},
		92: {
			name: 'Button Enemy Vehicle',
			help: 'Accurate fire from the Bren machine gun can shatter weapon sights, vision blocks, drive wheels, and stun enemy crews.',
			extra: 'Good vs. Tanks and Vehicles'
		},
		93: {
			name: 'Armor Piercing Burst',
			help: 'Load  Armor Piercing rounds into the Vickers Machine Gun.',
			extra: 'Good vs. Light Vehicles'
		},
		94: {
			name: 'Bren Carrier Self Repair',
			help: 'The Bren Carrier crew will carry out some basic, but necessary repairs.',
			extra: 'Repairing temporarily disables weapons and slows vehicle.'
		},
		97: {
			name: 'Button Enemy Vehicle',
			help: 'Accurate fire from the Bren machine gun can shatter weapon sights, vision blocks, drive wheels, and stun enemy crews.',
			extra: 'Good vs. Tanks and Vehicles'
		},
		98: {
			name: 'Call for M4 Sherman Calliope Reinforcement',
			help: 'An M4 Sherman equipped with a T34 Calliope Rocket Launcher is available for mobile Artillery Support.'
		},
		102: {
			name: 'Ambush Lock-Down',
			help: "Lock-down your Hetzer and enter a Camouflaged state. The Hetzer's first-strike out of Camouflage has powerful ambush bonuses."
		},
		103: {
			name: 'Camouflage',
			help: 'Camouflaged Units can only be detected if they engage in combat or if an Enemy Unit is in close proximity. While Camouflage is active, movement speed is reduced.'
		},
		104: {
			name: 'Camouflage',
			help: 'Camouflaged vehicles can be detected if they engage in combat or if an Enemy unit is in close proximity. While Camouflage is active, movement speed is reduced, the vehicle will also experience a penalty sight radius and camouflage-detection radius.'
		},
		106: {
			name: 'Camouflage',
			help: 'Camouflaged Units can only be detected if they engage in combat or if an Enemy Unit is in close proximity. While Camouflage is active, movement speed is reduced.'
		},
		107: {
			name: 'Camouflage',
			help: 'Camouflaged Units can only be detected if they engage in combat or if an Enemy Unit is in close proximity. While Camouflage is active, movement speed is reduced.'
		},
		112: {
			name: '25 Pounder Barrage',
			help: 'Fire a rapid barrage of 25 Pounder High Explosive shells into the targeted area.',
			extra: 'Area of Effect attack. Good vs. Infantry and Light Vehicles'
		},
		114: {
			name: '25 Pounder Barrage',
			help: 'Fire a rapid barrage of 25 Pounder High Explosive shells into the targeted area.',
			extra: 'Area of Effect attack. Good vs. Infantry and Light Vehicles'
		},
		116: {
			name: 'Armor Piercing Rounds',
			help: 'For a short duration, the crew  will load and fire ultra-high penetration APDS Armor Piercing rounds.',
			extra: 'Good vs. Tanks'
		},
		123: {
			name: 'Churchill Armored Vehicle Royal Engineers',
			help: 'The rugged Churchill provides the chassis for a variety of modifications designed to breach Normandy beach defenses. The AVRE fires a massive 290mm HESH warhead that can flatten buildings and defenses.',
			extra: 'Churchill AVRE'
		},
		124: {
			name: 'Churchill Crocodile',
			help: 'The Churchill Crocodile, along with other Churchill derivatives, is designed for the destruction of defenses, but has found wide utility against all targets. It maintains its normal 6 Pounder gun and adds a fearsome flame projector.',
			extra: 'Churchill Crocodile'
		},
		126: {
			name: 'Churchill Tank',
			help: 'The Churchill Infantry tank is heavily armored and slow; designed to move with and support infantry by knocking out pillboxes and other field fortifications.',
			extra: 'Churchill Tank'
		},
		127: {
			name: 'Tank Shock',
			help: 'Churchill tanks charge into enemy infantry causing near instant supression.',
			extra: 'Good vs. Infantry'
		},
		129: {
			name: 'Decoy Artillery Barrage',
			help: 'This barrage drops the smoke that precedes an artillery barrage. Use to fake out enemy commanders.',
			extra: 'Decoy Artillery Barrage'
		},
		130: {
			name: '25 Pounder Artillery Barrage',
			help: 'Small artillery barrage - use in conjunction with a decoy artillery ability.',
			extra: 'Area of Effect attack. Good vs. Infantry and Light Vehicles'
		},
		131: {
			name: 'Fire Petard Mortar Round',
			help: 'Fire the 290mm Petard Spigot Mortar round to clear obstacles, buildings, crewed weapons, and infantry.',
			extra: 'Area of Effect attack. Good vs. Infantry and Buildings.'
		},
		132: {
			name: 'Fire Canister Round',
			help: 'Loads the 37mm main gun with a shotgun-like canister charge that can blast an area with dozens of lethal projectiles.',
			extra: 'Good vs. Infantry'
		},
		134: {
			name: 'Flank Speed',
			help: 'The tank will push acceleration and top speed to the limit. Activating this ability will incur a slight fuel penalty for as long as the ability is active.'
		},
		135: {
			name: '25 Pounder Artillery Barrage',
			help: 'Lieutenants and Captains can call in an artillery barrage.',
			extra: 'Area of Effect attack. Good vs. Infantry and Light Vehicles'
		},
		138: {
			name: 'Hull Down Position',
			help: 'This vehicle can be toggled into and out of the Hull Down Position, which offers more protection to the vehicle when active.',
			extra: 'Static Defence Ability'
		},
		141: {
			name: 'Heroic Charge',
			help: 'The Lieutenant initiates a charge making all nearby squads immune to suppression, and increasing their offensive and defensive attributes.',
			extra: 'Area of Effect'
		},
		143: {
			name: 'Medical Supplies',
			help: 'Squads within the proximity of the Casualty Clearing Station will heal during the use of this ability.'
		},
		147: {
			name: '105mm Range Boost',
			help: "Fires an extremely long range barrage at target using the Priest's 105mm Howitzer. Can be fired into the fog of war.",
			extra: 'Area of Effect attack. Good vs. Infantry and Light Vehicles'
		},
		148: {
			name: '105mm Priest Self-Propelled Gun',
			help: 'The 105mm Howitzer-armed Priest is used by all Allied Forces during the invasion period. The powerful howitzer can fire a variety of artillery barrages.',
			extra: 'Good vs. Infantry and Buildings'
		},
		149: {
			name: 'Deploy Marksman',
			help: 'A trained marksman will deliver a single fatal shot to infantry units in the open or garrisoned in buildings or vehicles.'
		},
		157: {
			name: 'Rifle Smoke Grenade',
			help: 'Rifle grenadiers will fire a few smoke rounds to provide cover for nearby troops, or mask enemy emplacements.',
			extra: 'Creates smoke cover'
		},
		159: {
			name: 'Concealing Smoke',
			help: 'Break any suppression or pinning effects on the squad and envelope the Commandos in concealing smoke.'
		},
		160: {
			name: '3" Mortar Bombardment',
			help: 'Saturate an area with 3" mortar rounds.',
			extra: 'Good vs. Infantry'
		},
		161: {
			name: '3" Mortar Bombardment',
			help: 'Saturate an area with 3" mortar rounds.',
			extra: 'Good vs. Infantry'
		},
		162: {
			name: '3" Supercharge Barrage',
			help: 'Saturate an area from extreme distances with 3" mortar rounds.',
			extra: 'Good vs. Infantry'
		},
		163: {
			name: 'Throw Grenade',
			help: "The Squad will throw a Mk2 'Pineapple' Grenade.",
			extra: 'Good vs. Infantry, Infantry in Cover'
		},
		165: {
			name: 'Set Up',
			help: 'Order your Truck to Set Up at the selected location. A Set Up Truck can create units.',
			extra: 'Order HQ to Set Up'
		},
		166: {
			name: 'Set Up',
			help: 'Order your Truck to Set Up at the selected location. A Set Up Truck can create units.',
			extra: 'Order HQ to Set Up'
		},
		167: {
			name: 'Set Up',
			help: 'Order your Truck to Set Up at the selected location. A Set Up Truck can create units.',
			extra: 'Order HQ to Set Up'
		},
		175: {
			name: 'Counter Battery',
			help: 'Order this mortar to handle Counter Battery duties, firing back automatically at enemy artillery.',
			extra: 'Counter Battery'
		},
		176: {
			name: 'Counter Battery',
			help: 'Order this Priest to handle Counter Battery duties, firing back automatically at enemy artillery.',
			extra: 'Counter Battery'
		},
		177: {
			name: 'Cancel Counter Battery',
			help: 'Cancel the Counter Battery order.',
			extra: 'Cancel the Counter Battery'
		},
		178: {
			name: 'Cancel Counter Battery',
			help: 'Cancel the Counter Battery order.',
			extra: 'Cancel the Counter Battery'
		},
		179: {
			name: 'Creeping Barrage',
			help: 'Creeping barrages allow a well-trained gun crew to "walk" their artillery rounds along a predetermined firing path.',
			extra: 'Creeping Barrage'
		},
		180: {
			name: 'Creeping Barrage',
			help: 'Creeping barrages allow a well-trained gun crew to "walk" their artillery rounds along a predetermined firing path.',
			extra: 'Creeping Barrage'
		},
		181: {
			name: 'Creeping Smoke Barrage',
			help: 'The Cromwell Command Tank can call in smoke rounds along a path to provide excellent cover.',
			extra: 'Create a line of smoke cover.'
		},
		182: {
			name: 'Smoke Barrage',
			help: 'The King Tiger can call smoke cover.',
			extra: 'Create a line of smoke cover.'
		},
		183: {
			name: 'Barbed Wire Cutters',
			help: 'Wire Cutters are used to cut through Barbed Wire fences.'
		},
		184: {
			name: 'Barbed Wire Cutters',
			help: 'Wire Cutters are used to cut through Barbed Wire fences.'
		},
		185: {
			name: 'Fire Smoke Shell',
			help: 'A Smoke Round is fired from the vehicle, temporarily masking itself or targets.',
			extra: 'Provides Temporary Cover'
		},
		186: { name: 'Scorched Earth', help: 'Disable a Strategic Point so it cannot be captured.' },
		187: { name: 'Scorched Earth', help: 'Disable a Strategic Point so it cannot be captured.' },
		188: { name: 'Scorched Earth', help: 'Disable a Strategic Point so it cannot be captured.' },
		189: {
			name: 'Donkey Mines',
			help: 'In hopes they could be secreted behind enemy lines these Donkeys carried mines and other explosives where no one would think to check.',
			extra: 'Good vs. Infantry, Vehicles'
		},
		192: {
			name: 'Face Weapon',
			help: 'Some emplacements are capable of 360 degree rotation to prevent being flanked.'
		},
		193: {
			name: 'Face Weapon',
			help: 'Some emplacements are capable of 360 degree rotation to prevent being flanked.'
		},
		194: {
			name: 'Fire Smoke Shell',
			help: 'A Smoke Round is fired from the vehicle, temporarily masking itself or targets.',
			extra: 'Provides Temporary Cover'
		},
		196: {
			name: 'Maintain Command Range',
			help: 'Officer will follow targeted squad at a safer combat distance.'
		},
		197: {
			name: 'Maintain Command Range',
			help: 'Officer will follow targeted squad at a safer combat distance.'
		},
		198: {
			name: 'Maintain Command Range',
			help: 'Command tank will take follow targeted vehicle at a safer combat distance.'
		},
		199: {
			name: 'Maintain Support Range',
			help: 'Munitions Halftrack will follow targeted squad at a safer combat distance.'
		},
		200: {
			name: 'For the Fatherland',
			help: 'All Infantry are ideologically motivated, and fight better in their own Territory.'
		},
		201: {
			name: 'Glider HQ',
			help: 'Request a Glider Headquarters capable of producing Mortar Commandos, PIAT Commandos, and Heavy Machine Gun Commmandos.',
			extra: 'Cannot land in enemy base sectors.'
		},
		202: {
			name: 'Glider HQ',
			help: 'Request a Glider Headquarters capable of producing Mortar Commandos, PIAT Commandos, and Heavy Machine Gun Commmandos.'
		},
		203: {
			name: 'Glider with Tetrarch',
			help: 'Call in a glider loaded with a Tetrarch Tank. The glider is capable of producing more Tetrarch Tanks in territory.',
			extra: 'Cannot land in enemy base sectors.'
		},
		204: {
			name: 'Glider with Tetrarch',
			help: 'Call in a glider loaded with a Tetrarch Tank. The glider is capable of producing more Tetrarch Tanks in territory.'
		},
		205: {
			name: 'Glider',
			help: 'Call in a glider full of Commandos. The glider is capable of producing and reinforcing more Commandos in territory.',
			extra: 'Cannot land in enemy base sectors.'
		},
		206: {
			name: 'Glider',
			help: 'Call in a glider full of Commandos. The glider is capable of producing and reinforcing more Commandos in territory.'
		},
		207: {
			name: 'Detonate the Goliath',
			help: 'Goliaths are remote controlled Tanks packed with Explosives.',
			extra: 'Good vs. Tanks, Buildings'
		},
		208: {
			name: 'Armored Car Mine Drop',
			help: 'Armored Cars carried Mines to be placed along likely routes of Enemy advance.',
			extra: 'Good vs. Infantry, Vehicles'
		},
		209: {
			name: 'Armor Piercing Burst',
			help: 'M2 Armor Piercing (AP) ball ammunition is loaded into the Machine Gun, making it very effective against Light Vehicles. HMG must be set up and able to fire at the target for the rounds to work.',
			extra: 'Good vs. Light Vehicles'
		},
		243: {
			name: 'Medical Kit',
			help: 'Use of the Medical Kit will heal your Squad over time. This Medical Kit can only be used in friendly territory.'
		},
		244: {
			name: 'Field Medical Kit',
			help: 'Use of the Medical Kit will heal your Squad over time. This Medical Kit can be used anywhere.'
		},
		245: { name: 'Field Medical Kit', help: 'Using the medical kit will heal the squad.' },
		247: {
			name: 'Disable Free-Fire',
			help: 'Mortars will be ordered not to Free-Fire, instead only engaging enemy targets when ordered via a barrage.'
		},
		248: {
			name: 'Munitions Halftrack Mine Drop',
			help: 'Munitions Halftrack can place mines along likely routes of Enemy advance.',
			extra: 'Good vs. Infantry, Vehicles'
		},
		254: {
			name: 'Overwatch Barrage',
			help: 'Order this 25 pounder crew to automatically fire at any visible enemy units within the overwatch radius.',
			extra: 'Overwatch Barrage'
		},
		255: {
			name: 'Cancel Overwatch',
			help: 'Cancel the overwatch.',
			extra: 'Overwatch Barrage Remove'
		},
		256: {
			name: 'Overwatch Barrage',
			help: 'Order this Artillery Piece to watch an area for enemy movement and fire only when the enemy occupies that area.',
			extra: 'Good vs. Infantry'
		},
		257: { name: 'Cancel Overwatch', help: 'Cancel the overwatch.', extra: 'Good vs. Infantry' },
		258: {
			name: 'Overwatch Priest Barrage',
			help: "Target the Priest's 105mm to automatically fire at any visible enemy units within the overwatch radius.",
			extra: 'Overwatch Barrage'
		},
		259: {
			name: 'Cancel Overwatch',
			help: 'Cancel the overwatch.',
			extra: 'Overwatch Barrage Remove'
		},
		263: {
			name: 'Secure Sector',
			help: 'Lock the Car down and increase the resources gathered in the sector. The Car will become immobile in its secured state.',
			extra: 'Gather resources faster'
		},
		264: {
			name: 'Get Mobile',
			help: 'The Logistik Car will be able to move and territory will be unsecured.',
			extra: 'Get Mobile'
		},
		266: {
			name: 'Anti Building Incendiary Device',
			help: 'Fallschirmjager throw an incendiary device with a very long burn time, effective against buildings and emplacements.',
			extra: 'Good vs. Emplacements and Buildings'
		},
		267: {
			name: 'Throw Anti Tank Grenade',
			help: 'Throw an effective Anti Tank Grenade. This Grenade is not effective against infantry units in cover.',
			extra: 'Bad vs. Infantry in Cover'
		},
		268: {
			name: 'Fire Panzerfaust',
			help: 'Fire the disposable 100mm Panzerfaust at Enemy Armor or Structures.'
		},
		269: {
			name: 'Throw two Anti Tank Grenades',
			help: 'Throw Two Anti Tank Grenades. This Grenade is not effective against infantry units in cover.',
			extra: 'Bad vs. Infantry in Cover'
		},
		270: {
			name: 'Focused Firing',
			help: 'The Light AT Gunner exposes the precision of his weapon by taking careful aim with every shot, slowing the rate of fire but capable of hitting even a moving infantry target with utmost accuracy.',
			extra: 'Good vs. Infantry'
		},
		272: {
			name: "Henschel 'PanzerKnacker' support",
			help: 'A Henschel Hs. 129 ground attack plane armed with a 75mm cannon will fly air coverage over the area specified, targeting enemy vehicles and tanks.',
			extra: 'Good vs. Tanks'
		},
		273: {
			name: 'Hummel 150mm Howitzer Barrage',
			help: 'The Hummel will fire a powerful barrage of 150mm shells at the specified target. Can be fired into the Fog of War.',
			extra: 'Area of Effect attack. Good vs. Infantry and Light Vehicles'
		},
		274: {
			name: 'Hummel 150mm Howitzer Barrage',
			help: 'The Hummel will fire a powerful barrage of 150mm shells at the specified target. Can be fired into the Fog of War.',
			extra: 'Area of Effect attack. Good vs. Infantry and Light Vehicles'
		},
		276: {
			name: 'Hummel 150mm Self-Propelled Howitzer',
			help: 'Order a Hummel 150mm Howitzer to the battlefield for devastating artillery support.'
		},
		277: {
			name: 'Incendiary Mortar Round',
			help: 'Incendiary rounds fired into the targeted area will burn any entrenched infantry and damage structures.',
			extra: 'Good vs. Infantry'
		},
		278: {
			name: 'Fallschirmjager Infiltration',
			help: 'A squad of Fallschirmjager who have infiltrated the battlefield will emerge from targeted buildings, or from Off-map if not targeted on buildings.',
			extra: 'Target buildings'
		},
		279: {
			name: 'Luftwaffe Ground Forces',
			help: 'Luftwaffe ground forces are light combat troops also capable of constructing simple defenses and AA weapons.'
		},
		283: {
			name: 'Booby Traps',
			help: 'Order this squad to prepare the target with booby traps that will be triggered by enemy units.',
			extra: 'Leave a nasty surprise for enemy units.'
		},
		284: {
			name: 'Hetzer',
			help: 'The diminutive Hetzer mounted the same powerful Pak39 as used on the Panzer IV in well-armored chassis that was also small enough to easily conceal.',
			extra: 'Good vs. Tanks'
		},
		285: {
			name: 'Jagdpanther',
			help: 'The Jagdpanther is a heavy tank destroyer armed with the same 88mm Pak 43 as the King Tiger. The Jagdpanther is rare, and so is allocated only once per battle.',
			extra: 'Good vs. Tanks'
		},
		286: {
			name: 'Panther Battle Group',
			help: 'Two Panther tanks will arrive to support offensive operations.',
			extra: 'Good vs. Tanks'
		},
		287: { name: 'Sprint', help: 'Sprinting will make a squad move faster for a short time.' },
		288: {
			name: 'Rocket Barrage',
			help: 'Barrage the area ordered with six Wurfrahmen 40" Heavy Rockets',
			extra: 'Area of Effect attack. Good vs. Light Vehicles and Buildings'
		},
		289: {
			name: '81mm Mortar Bombardment',
			help: 'Several high-angle 81mm Mortar Rounds will be fired into the targeted area.',
			extra: 'Good vs. Infantry'
		},
		290: {
			name: 'Throw Incendiary Grenade',
			help: 'The squad will throw a chemical Incendiary Grenade that will burn the selected area for a period of time.',
			extra: 'Good vs. Infantry, Infantry in Cover'
		},
		291: {
			name: 'Suppressive Volley Fire',
			help: 'Rapid rifle fire from the G43s will force enemy units to the ground and keep them moving slowly for a short period of time.',
			extra: 'Good vs. Infantry'
		},
		292: {
			name: 'Wirbelwind',
			help: 'The Wirbelwind mounts a rapid firing 20mm flakvierling 38 on a Panzer IV chassis. This vehicle provides excellent air and ground protection for armored columns.',
			extra: 'Good vs. Infantry'
		},
		294: {
			name: 'Call In Reinforcements',
			help: 'Infantry Reinforcements. Use these Units to rebuild and continue the struggle.'
		},
		296: {
			name: 'Goliath Drop',
			help: 'Halftrack can drop a Goliath Remote Controlled Bomb.',
			extra: 'Good vs. Tanks, Buildings, Infantry.'
		},
		297: {
			name: 'Rapid Fire Artillery',
			help: 'When locked down, the Hummel is immobile, but can fire its massive 150mm shells much further and faster.'
		},
		298: {
			name: 'Site Main Gun',
			help: 'The Marder III can sacrifice mobility to gain more destructive power from its 75mm Pak 40 Anti Tank gun.'
		},
		299: {
			name: 'Rapid Fire',
			help: "At the tradeoff of mobility, the Panzer IV's crew will all help to load and fire the main gun as rapidly as possible.",
			extra: 'RAPID FIRE'
		},
		300: {
			name: 'Munitions Halftrack Goliath Drop',
			help: 'Munitions Halftracks can drop a Goliath Remote Controlled Bomb.',
			extra: 'Good vs. Tanks, Buildings, Infantry.'
		},
		301: {
			name: 'Overdrive',
			help: 'Order the Light Armored Car to move at maximum speed. Activating this ability will incur a slight fuel penalty for as long as the ability is active.'
		},
		302: {
			name: 'Tread Breaker',
			help: 'This aimed shot can disable the wheels, engine, or treads of an enemy vehicle, immobilizing it.',
			extra: 'Aimed Shot'
		},
		303: {
			name: 'Call for Pershing Reinforcement',
			help: 'An M26 Pershing Heavy Tank is available for support.'
		},
		305: {
			name: 'Enable Point',
			help: 'Repair a damaged point',
			extra: 'Re-enable a point so it can once again be captured'
		},
		306: {
			name: 'Enable Point',
			help: 'Repair a damaged point',
			extra: 'Re-enable a point so it can once again be captured'
		},
		309: { name: 'Off-Map Combat Group', help: 'A small Reinforcement Division is available.' },
		311: { name: 'Off-Map Combat Group', help: 'A small Reinforcement Division is available.' },
		312: { name: 'Repair', help: 'Repair a Structure or Vehicle for a nominal Resource cost.' },
		313: {
			name: 'Advanced Repair',
			help: 'Repair a Structure or Vehicle for a nominal Resource cost.'
		},
		314: {
			name: 'Over Repair',
			help: 'Sappers can repair much faster and can make vehicles sturdier than they were originally.'
		},
		315: {
			name: 'Rudimentary Repair',
			help: 'Low quality repair of a Structure or Vehicle for a nominal Resource cost.'
		},
		316: {
			name: 'Rudimentary Repair',
			help: 'Low quality repair of a Structure or Vehicle for a nominal Resource cost.'
		},
		317: {
			name: 'Advanced Repair',
			help: 'High quality repair of a Structure or Vehicle for a nominal Resource cost.'
		},
		319: {
			name: 'Advanced Repair',
			help: 'High quality repair of a Structure or Vehicle for a nominal Resource cost.'
		},
		327: {
			name: "Withdraw to Captain's Position",
			help: "Withdraw your units to the Captain's current position."
		},
		328: {
			name: 'Propaganda War',
			help: 'Superior Propaganda efforts demoralize Enemy Troops, forcing a retreat to their HQ area.',
			extra: 'Good vs. Infantry'
		},
		329: {
			name: 'Force Retreat',
			help: 'Force any Enemy Infantry Squad to immediately retreat.',
			extra: 'Good vs. Infantry'
		},
		330: { name: 'Salvage Wrecks', help: 'Salvage Munitions from Wrecked Vehicles.' },
		331: {
			name: 'Mine Drop',
			help: 'Mines are best placed along likely routes of an Enemy advance.',
			extra: 'Good vs. Infantry, Vehicles'
		},
		332: {
			name: 'Teller Mine Drop',
			help: 'Teller Mines require at least 150kg of pressure to activate, therefore only vehicles or tanks will trigger this powerful explosive charge.',
			extra: 'Good vs. Vehicles'
		},
		333: {
			name: 'Sector Artillery',
			help: 'Have the selected sector monitored for enemy activity, saturating the area with artillery until that enemy activity ceases.',
			extra: 'Sector Attack'
		},
		335: {
			name: 'Toggle Mineclearing',
			help: 'When engaged, the Sherman Crab attachment can safely explode Mines.'
		},
		431: {
			name: 'Supervision',
			help: 'Reduces the unit creation time of any Supervised Structure. Officer will Supervise until ordered elsewhere.'
		},
		444: {
			name: 'Divert Supplies',
			help: "Enables the Funkwagen 'Vampire' to divert resources produced  from an enemy sector. It will also deny the enemy resources in a connected supply line. When deployed, infantry can be detected in the Fog of War."
		},
		446: {
			name: 'Air-Dropped SD-2 Butterfly Bombs',
			help: 'Butterfly Bombs are dropped from the air and blanket the selected area. The Butterfly Bombs are a capable anti-personnel mine.',
			extra: 'Good vs. Infantry'
		},
		467: {
			name: 'V1 Rocket',
			help: 'Unleash the vengeance weapons! A V1 rocket can be ordered into the chosen area.',
			extra: 'Good vs. Everything'
		},
		468: {
			name: 'Victor Targeter',
			help: 'Unleash the vengeance weapons! A V1 rocket can be ordered into the chosen area.',
			extra: 'V1'
		},
		473: {
			name: 'Victor Target',
			help: 'The Victor Target will order all heavy artillery pieces (25 Pounders and Priests) to fire simultaneously at the same point.  Artillery rounds fired to bombard the Victor Target will ignore their usual range constraints. Artillery pieces ordered to Counterbattery or Overwatch an area will not join in the barrage.'
		},
		474: {
			name: 'Victor Targeter',
			help: 'Captains have the command authority to designate a Victor target, which all on-map artillery will saturate with fire.',
			extra: 'Fires all on-map artillery'
		},
		508: {
			name: 'Fire Smoke Shell',
			help: 'A Smoke Round is fired from the vehicle, temporarily masking itself or targets.',
			extra: 'Provides Temporary Cover'
		},
		509: {
			name: 'Sprint',
			help: 'Sprinting will make the squad faster and less prone to suppression for a short time.',
			extra: 'Left-click icon to activate Sprint.'
		},
		510: {
			name: 'Infantry Assault Team',
			help: 'Call in a Squad of Stormtroopers for Reinforcement.'
		},
		511: { name: 'Flank Speed', help: 'Accelerate Tiger to maximum speed' }
	},
	ebps: {
		1501: { name: 'Flakvierling 38 20mm AA', help: 'Flakvierling 38 20mm AA' },
		1503: { name: 'M2 60mm Mortar', help: 'M2 60mm Mortar' },
		1505: { name: 'Minesweeper' },
		1506: { name: 'MG42', help: 'MG42 Heavy Machine Gun' },
		1509: {
			name: 'Tank Depot',
			help: "Primary Tank Production Structure. Deploys M10's, M18 Hellcats, M4 Shermans as well as Sherman Crocodiles. Also contains upgrades for the M4 Sherman."
		},
		1511: {
			name: 'Barbed Wire',
			help: 'Barbed Wire fences stop Enemy Troops from entering your Territory.'
		},
		1513: {
			name: 'Barbed Wire',
			help: 'Barbed Wire fences stop Enemy Troops from entering your Territory.'
		},
		1515: {
			name: 'Barracks',
			help: 'Deploy Riflemen Squads and Jeeps from the Barracks. Also contains upgrades for the Riflemen.'
		},
		1516: {
			name: 'Medic Station',
			help: 'Houses Medics whose sole purpose is to return Casualties back to the Station.'
		},
		1527: { name: 'Destroyed HQ' },
		1529: { name: 'Destroyed HQ' },
		1530: { name: 'Destroyed HQ' },
		1531: { name: 'Destroyed HQ' },
		1533: { name: 'Destroyed HQ' },
		1534: { name: 'Destroyed HQ' },
		1537: {
			name: 'Machine Gun Emplacement',
			help: 'Machine Gun Emplacements are excellent at suppressing Enemy Troops.'
		},
		1539: {
			name: 'Motor Pool',
			help: 'Primary Vehicle Production Structure. Deploys Armored Cars, Halftracks and 57mm Anti Tank guns.'
		},
		1540: { name: 'Supply Yard', help: 'Logistic Support. Reduces unit Upkeep and Support costs.' },
		1541: { name: 'Sand Bags', help: 'Sand bags provide Troops with cover.' },
		1542: { name: 'Sand Bags', help: 'Sand bags provide Troops with cover.' },
		1543: { name: 'Sand Bags', help: 'Sand bags provide Troops with cover.' },
		1544: {
			name: 'Observation Post',
			help: 'Secure Sectors, which increases Resource production of that Sector and prevents enemy units from capturing that Sector.'
		},
		1549: {
			name: 'Weapons Support Center',
			help: 'Secondary Troop Production Structure. Deploys Heavy Machine Gun teams, Mortar Teams and Snipers.'
		},
		1550: {
			name: 'Tank Traps',
			help: 'Tank Traps are used to stop Enemy Armor from penetrating friendly Territory.'
		},
		1551: {
			name: 'Tank Traps',
			help: 'Tank Traps are used to stop Enemy Armor from penetrating friendly Territory.'
		},
		1552: { name: 'Triage Center', help: 'Triage Centers heals any nearby Soldiers.' },
		1554: { name: 'Mines', help: 'Mines are good at defending vulnerable positions.' },
		1556: { name: 'Mines', help: 'Mines are good at defending vulnerable positions.' },
		1601: { name: '25 Pounder Gun Howitzer' },
		1611: {
			name: 'M2 105mm Howitzer',
			help: 'The M2 105mm Howitzer provides long range indirect fire support.'
		},
		1619: { name: 'P47 Thunderbolt' },
		1620: { name: 'P47 Thunderbolt' },
		1623: { name: 'M26 Pershing' },
		1625: { name: 'Boat' },
		1626: { name: 'T17 Armored Car' },
		1629: {
			name: '17 Pounder AT Gun',
			help: "The 17 Pounder is possibly the most fearsome Anti Tank gun in any combatant nation's inventory. The weapon is large and cumbersome, which limits its use against infantry and fast moving light vehicles."
		},
		1630: {
			name: 'Barbed Wire',
			help: 'Barbed Wire fences stop Enemy Troops from entering your Territory.'
		},
		1631: {
			name: 'Barbed Wire',
			help: 'Barbed Wire fences stop Enemy Troops from entering your Territory.'
		},
		1633: {
			name: 'Bofors 40mm Cannon',
			help: 'The Bofors 40mm cannon is dangerous to low flying aircraft and light vehicles, but its light shell has little effect on heavy armor, and the barrel cannot depress low enough to effectively target infantry.'
		},
		1634: {
			name: 'Casualty Clearing Station',
			help: 'Houses Medics that return Casualties back to the Station; if enough Casualties are collected a new squad will be granted. Units within proximity of the casualty clearing center can be healed with Medical Supplies.'
		},
		1635: { name: 'Mines', help: 'Mines are good at defending vulnerable positions.' },
		1636: {
			name: 'Detector for Radio Triangulation',
			help: 'Three Radio Detectors will enable direction finding and reveal enemy units within a triangular boundary. The enemy units are visible on the minimap and tactical map.'
		},
		1638: { name: 'Glider' },
		1641: {
			name: '25 Pounder Gun Howitzer',
			help: 'Long range, effective accuracy, and a good rate of fire are hallmarks of the 25 Pounder Artillery in use by British and Commonwealth forces.'
		},
		1643: {
			name: 'Vickers Machine Gun Emplacement',
			help: 'A well fortified emplacement is constructed for the venerable .303 Vickers Machine Gun, capable of sustained heavy suppressive fire.'
		},
		1644: {
			name: '3" Mortar Emplacement',
			help: 'The Mortar Emplacement contains a 3" mortar capable of lobbing rounds over objects at long range.'
		},
		1646: { name: 'Sand Bags', help: 'Sand bags provide Troops with cover.' },
		1648: {
			name: 'Slit Trench',
			help: 'Slit trenches provide excellent cover for Infantry, especially from artillery fire. Grenades and incendiary devices are dangerous to units in slit trenches.'
		},
		1693: { name: 'Destroyed HQ' },
		1694: { name: 'Kangaroo Carrier', help: 'Kangaroo Carrier' },
		1695: { name: 'Priest Self-Propelled Artillery' },
		1698: { name: 'Staghound Armoured Car' },
		1699: { name: 'Stuart Light Tank' },
		1701: { name: 'Bren Carrier' },
		1703: { name: 'Mines', help: 'Mines are good at defending vulnerable positions.' },
		1704: {
			name: 'Bunker',
			help: 'Primary defensive Structure. Can upgrade to an Aid Station, Repair Station or an MG Emplacement.'
		},
		1705: {
			name: 'Observation Post',
			help: 'Secure Sectors, which increases Resource production of that Sector and prevents enemy units from capturing that Sector.'
		},
		1708: {
			name: 'Barbed Wire',
			help: 'Barbed Wire fences stop Enemy Troops from entering your Territory.'
		},
		1709: {
			name: 'Wehrmacht Quarters',
			help: 'Deploys Volksgrenadier Squads, Snipers, Heavy Machine Gun teams, Schwimmwagens and Motorcycles.'
		},
		1711: {
			name: 'Panzer Command',
			help: 'Deploys the most powerful Units in the Axis Army. Panther tanks, Panzer IV tanks, Ostwind Flak tanks, and Knights Cross Holders.'
		},
		1713: {
			name: 'Sturm Armory',
			help: 'Deploys the Officer, 234 Heavy Armored Cars, Stug tanks, Geschutzwagens, and the Nebelwerfer Rocket Artillery.'
		},
		1730: { name: 'Destroyed HQ' },
		1732: { name: 'Destroyed HQ' },
		1733: { name: 'Destroyed HQ' },
		1738: { name: 'Destroyed HQ' },
		1740: {
			name: 'Krieg Barracks',
			help: 'Deploys Grenadier Squads, Mortar Teams, Pak 38 Anti Tank guns, and Halftracks.'
		},
		1742: {
			name: 'Kampfkraft Centre',
			help: 'Contains the upgrades to request experienced Veteran Troops and Tanks. Veterans are well trained to deal with battlefield situations.'
		},
		1743: { name: 'Sand Bags', help: 'Sand Bags provide Troops with cover.' },
		1748: {
			name: 'Tank Traps',
			help: 'Tank Traps are used to stop Enemy armor from penetrating friendly Territory.'
		},
		1786: { name: 'Volksgrenadiers' },
		1787: { name: 'Build Defensive Structures', help: 'Construct Sandbags and Barb Wire Fences.' },
		1797: {
			name: '88mm Flak 36 AT/AA',
			help: 'The 88mm Flak 36 provides fearsome Anti Tank and Anti Air firepower.'
		},
		1839: { name: 'King Tiger' },
		1840: { name: 'King Tiger' },
		1850: {
			name: 'Barbed Wire',
			help: 'Barbed Wire fences stop Enemy Troops from entering your Territory.'
		},
		1851: {
			name: 'Barbed Wire',
			help: 'Barbed Wire fences stop Enemy Troops from entering your Territory.'
		},
		1859: {
			name: 'Headquarters',
			help: 'Deploy Pioneers and escalate Battle Phases to call in additional Reinforcements.'
		},
		1860: {
			name: 'Headquarters',
			help: 'Deploy Pioneers and escalate Battle Phases to call in additional Reinforcements.'
		},
		1861: {
			name: 'Headquarters',
			help: 'Deploy Pioneers and escalate Battle Phases to call in additional Reinforcements.'
		},
		1862: { name: 'Destroyed HQ' },
		1863: { name: 'Destroyed HQ' },
		1864: { name: 'Destroyed HQ' },
		1867: { name: 'Destroyed HQ' },
		1870: {
			name: 'Kampfgruppe Kompanie',
			help: 'Makes available the Infantry Halftrack, Mortar Halftrack, and Tank Buster Squads. Available upgrades can increase territory capture rate of Infantry squads and improve their repair skills.'
		},
		1871: {
			name: 'Logistik Kompanie',
			help: "Makes available the Scout Car, Munitions Halftrack and 250/3 Funkwagen 'Vampire' Halftrack. Upgrades will equip squads with Anti Tank Grenades and increase the size of infantry squads."
		},
		1872: {
			name: 'Panzer-Support Kommand',
			help: 'Initially produces the Light Anti Tank Halftrack and the Bergetiger Repair and Recovery vehicle. Can be upgraded to produce the Panzer IV Infantry Support Tank and the Hotchkiss Light Tank. A Veteran Sergeant makes squads tougher, harder to suppress, and gain experience more rapidly.'
		},
		1873: {
			name: 'Panzer-Jager Kommand',
			help: 'Initially produces Assault Grenadiers and a 20mm Armored Car. Can be upgraded to produce the Marder III  Tank Hunter. Infantry can be improved via the Group Zeal upgrade.'
		},
		1874: { name: 'Sand Bags', help: 'Sand Bags provide Troops with cover.' },
		1875: {
			name: 'Road Blocks',
			help: 'Road Blocks are extremely tough piles of junk material scraped together to block off an area. Roadblocks must be destroyed and cannot be crushed by any tank.'
		},
		1879: {
			name: 'Teller Mines',
			help: 'Teller Mines require at least 150kg of pressure to activate, therefore only vehicles or tanks will trigger the powerful explosive charge.'
		},
		1897: { name: 'Scout Car' },
		1902: { name: 'Infantry Halftrack' },
		1909: {
			name: '88mm Flak 36 AT/AA',
			help: 'The 88mm Flak 36 provides fearsome Anti Tank and Anti Air firepower.'
		},
		1914: { name: 'Flakvierling 38 20mm AA', help: 'Construct a Flakvierling 38 20mm.' }
	},
	sbps: {
		2: {
			name: 'Airborne',
			help: 'Well trained Paratroopers can destroy Enemy positions with Satchel Charges, and can be equipped with M18 Recoilless Rifles for addition protection against all Vehicle types.',
			extra: 'Good vs. Buildings'
		},
		10: {
			name: 'Engineers',
			help: 'Call in Engineers to construct and Repair Structures. Engineers can be equipped with Minesweepers, Flamethrowers, Wire Cutters and Demolition Charges.',
			extra: 'Primary Builder. Good vs. Buildings.'
		},
		15: {
			name: 'Heavy Machine Gun Team',
			help: 'Utilizes a .30 cal M1917 Heavy Machine Gun to lay down an enormous amount of firepower that is especially effective against massed Infantry. armor piercing bullets are effective against Light Vehicles.',
			extra: 'Good vs. Infantry and Light Vehicles'
		},
		40: {
			name: 'Mortar Team',
			help: 'The M2 60mm Mortar can drop Mortar Bombs on concentrations of Infantry, Heavy Weapons, or Squads in Buildings. Use this weapon to break through defensive impasses.',
			extra: 'Good vs. Infantry, Infantry in cover'
		},
		48: {
			name: 'Riflemen',
			help: 'Versatile soldier in attack or defense. Grenades, Sticky Bombs and M1918 BARs provide protection against multiple threat types.',
			extra: 'Good vs. Infantry, Light vehicles.'
		},
		54: {
			name: 'Sniper',
			help: 'Highly skilled Sharpshooter with scoped M1903 Rifle, effective against all Infantry. Can use camouflage ability.',
			extra: 'Good vs. Infantry'
		},
		61: {
			name: 'Jeep',
			help: "The Jeep's speed makes it an ideal Reconnaissance unit that excels at hunting down Enemy Snipers.",
			extra: 'Good vs. Snipers, Support Weapons'
		},
		63: {
			name: 'M10 Tank Destroyer',
			help: 'The M10 sacrifices armor protection for a heavier main Gun. The M10 relies on its powerful 3 inch main Gun and its speed to tackle Enemy Tanks.',
			extra: 'Good vs. Tanks'
		},
		65: {
			name: 'M18 Hellcat',
			help: 'The M18 Hellcat is a tank destroyer that comes equipped with .50 cal machine gun and the ability camouflage.  It has a reduced frontal armor penetration capabilities.',
			extra: 'Good vs. Tanks'
		},
		67: {
			name: 'M1 57mm Anti Tank Gun',
			help: 'The M1 57mm Anti Tank Gun offered reasonable protection against Enemy Tanks, but could also tackle hardened Structures. APC Shells improve armor penetration.',
			extra: 'Good vs. Tanks'
		},
		74: {
			name: 'M3 Halftrack',
			help: 'Transport and Reinforce Troops, or equip the Halftrack with a Quad .50 cal Turret.',
			extra: 'Transport Troops'
		},
		75: {
			name: 'M4 Sherman',
			help: 'The M4 Sherman is the workhorse of the Allied armies in Normandy. Upgrades to its main gun, a .50 cal Machine Gun, a Crab mine flail, and Smoke Dischargers can carry the M4 through to the end of any battle.',
			extra: 'Good vs. Infantry'
		},
		77: {
			name: "M4 'Crocodile' Sherman",
			help: 'The Crocodile is an assault Tank and comes equipped with a Flamethrower but cannot fire its main Gun. Can be equipped with a Bulldozer to clear obstacles.',
			extra: 'Good vs. Infantry'
		},
		79: {
			name: 'M8 Armored Car',
			help: 'Fast reconaissance Vehicle which is good at harrassing Enemy Infantry and destroying Light Vehicles. Can be equipped with better armor and an .50 HMG.',
			extra: 'Good vs. Infantry, Light Vehicles'
		},
		83: {
			name: 'T17 Armored Car',
			help: 'The T17 is a heavier armored car variant tested by US forces, able to use White Phosphorus rounds against enemy targets.',
			extra: 'Good vs. Infantry'
		},
		87: {
			name: 'Captain',
			help: 'The lightly-armed Captain imparts powerful defensive bonuses to units and structures within the sector that he occupies.',
			extra: 'Commander. Imparts Defensive Bonuses'
		},
		88: {
			name: 'HMG Commandos',
			help: 'A Commando Section equipped with a .303 Vickers Heavy Machine Gun, effective against massed infantry.',
			extra: 'Good vs. Infantry'
		},
		89: {
			name: 'Mortar Commandos',
			help: 'A Commando Section equipped with the standard British 3" Mortar.',
			extra: 'Good vs. Infantry'
		},
		91: {
			name: 'PIAT Commandos',
			help: 'A Commando Section armed with PIAT Anti Tank weapons.',
			extra: 'Good vs. Infantry'
		},
		92: {
			name: 'Commandos',
			help: 'British Commandos are tough, elite troops armed with light weapons and explosives.',
			extra: 'Good vs. Infantry'
		},
		114: {
			name: 'Lieutenant',
			help: 'Lieutenants provide much of the offensive punch of the infantry sections, imparting powerful attack and morale bonuses in a radius. Squads are more mobile with a Lieutenant nearby.',
			extra: 'Commander. Imparts Offensive Bonuses and Mobility'
		},
		121: {
			name: 'Sappers',
			help: 'Sappers are combat engineers capable of specialized upgrades, general combat related tasks, and building heavy defenses.',
			extra: 'Builds Heavy Defenses. Good vs. Infantry'
		},
		123: {
			name: 'Infantry Section',
			help: 'British Infantry are dogged, well-trained soldiers with a variety of versatile upgrades that enable them to tackle a variety of combat tasks.',
			extra: 'Good vs. Infantry, Light Vehicles. Constructs Defenses'
		},
		133: {
			name: 'Bren Carrier',
			help: 'The ubiquitous Bren Carrier can transport a section of Infantry or an officer. Can be outfitted with a Vickers MMG for added  fire support.',
			extra: 'Transport. Good vs. Infantry'
		},
		138: {
			name: 'Cromwell Command Tank',
			help: 'The unarmed Command Tank uses a dummy gun barrel to mask its true identity from the enemy. Massive radios crowd the turret, allowing communication with nearby tank squads and other command elements.',
			extra: 'Commander. Improves Nearby Tank Effectiveness. Unarmed'
		},
		142: {
			name: 'Cromwell',
			help: 'The Cromwell mates a 75mm main gun with reasonable armor and a powerful V12 engine. The Cromwell offers similar performance to the M4 Sherman, but is a lower profile target that is harder to hit - a fact that is of great interest to its crews.',
			extra: 'Good vs. Infantry, Tanks'
		},
		149: {
			name: 'Kangaroo Carrier',
			help: 'The Kangaroo Carrier is a heavy armored personnel carrier. With no standard turret the Kangaroo relies on its large hold and garrisoned squads to give it offensive value.',
			extra: 'Transport Troops'
		},
		151: {
			name: 'Sherman Firefly',
			help: 'A very powerful 17 Pounder Anti Tank Gun added to a relatively standard Sherman creates the Firefly. British and Commonwealth forces can finally engage and kill heavy enemy tanks at very long ranges.',
			extra: 'Excellent vs. Tanks'
		},
		153: {
			name: 'Staghound Armoured Car',
			help: 'Built by the US, the Staghound was adopted by the British as a versatile command and recon vehicle.  Can be equipped with an M2HB .50 cal Machine Gun.'
		},
		154: {
			name: 'Stuart Light Tank',
			help: 'The Stuart is used by almost all Allied forces. Too light to engage heavy armor, its speed means it excels in the reconnaissance role. Can fire a canister round that is lethal to infantry targets.',
			extra: 'Good vs. Light Vehicles'
		},
		155: {
			name: 'Tetrarch',
			help: 'The 2 Pounder equipped Tetrarch tank was designed to be glider deployed, and was therefore lightly armored. It provided much needed fire support to units operating behind enemy lines.',
			extra: 'Good vs. Infantry, Light Vehicles'
		},
		162: {
			name: 'Grenadiers',
			help: 'Formed the backbone of the Axis forces. Can be equipped with MG42s and Panzerschrecks.',
			extra: 'Good vs. Infantry'
		},
		164: {
			name: 'MG42 Heavy Machine Gun',
			help: 'An MG42 Heavy Machine Gun with a fire rate of 1200 rounds per minute can devastate Enemy Infantry.',
			extra: 'Good vs. Infantry'
		},
		182: {
			name: "Knight's Cross Holders",
			help: 'Elite assault Troops equipped with MP44s. Excel in all combat situations.',
			extra: 'Good vs. Infantry'
		},
		186: {
			name: 'Gr. 34 8cm Mortar Team',
			help: 'The Granatewerfer 34 8cm Mortar provides indirect fire support.',
			extra: 'Good vs. Infantry'
		},
		187: {
			name: 'Officer',
			help: 'Highly experienced officers who led by example fighting from the front.',
			extra:
				'Can Supervise Buildings to improve production, call in Mortar fire on Enemy Units, and Rout Enemy forces.'
		},
		188: {
			name: 'Pioneers',
			help: 'Primary Builder. Can build and Repair Structures. Pioneers can be equipped with Minesweepers or Flamethrowers and can salvage destroyed Vehicles for supplies.',
			extra: 'Good vs. Buildings'
		},
		189: {
			name: 'Sniper',
			help: 'Highly skilled Sharpshooter, effective against all Infantry. Can use Camouflage ability.',
			extra: 'Good vs. Infantry'
		},
		207: {
			name: 'Volksgrenadiers',
			help: 'Light Infantry with little combat experience.',
			extra: 'Good vs. Infantry'
		},
		214: {
			name: '150mm Nebelwerfer Rocket Battery',
			help: 'The Nebelwerfer can launch six 150mm Rockets.',
			extra: 'Area of Effect Barrage. Good vs. Infantry'
		},
		215: {
			name: 'Pak 38 50mm Anti Tank Gun',
			help: 'Long range Anti Tank weapon with good armor penetration, but little area of effect. The Pak 38 can Camouflage to ambush Enemy Vehicles and can get several shots off before it reveals itself.',
			extra: 'Good vs. Tanks, can ambush attack.'
		},
		222: {
			name: 'Schwimmwagen Type 166',
			help: 'A fast reconnaissance vehicle, the Schwimmwagen Type 166 can utilize its speed to mercilessly hunt down elusive Snipers.',
			extra: 'Good vs. Snipers, Weapon Teams'
		},
		228: {
			name: 'Geschutzwagen',
			help: 'Equipped with a Pak40 75mm cannon, this highly mobile, anti-tank gun can lock-down and eliminate enemy targets at a rapid rate.',
			extra: 'Good vs. Tanks'
		},
		229: {
			name: 'Goliath',
			help: 'A small remote controlled Bomb that can inflict massive area effect damage upon detonation.',
			extra: 'Good vs. Tanks, Buildings, Bridges.'
		},
		230: {
			name: 'Sdkfz 251 Halftrack',
			help: "Can transport and Reinforce Troops in and out of battle. Can be equipped with Wurfrahmen 40 rockets ('Stuka zu Fuss') or Flamethrowers.",
			extra: 'Troop Transport'
		},
		237: {
			name: 'Motorcycle',
			help: 'A fast reconnaissance Motorcycle, it can utilize its speed to mercilessly hunt down elusive Snipers.',
			extra: 'Good vs. Snipers, Weapon Teams'
		},
		240: {
			name: 'Ostwind Flakpanzer',
			help: 'Armed with a rapid firing 37mm Gun that can target Aircraft, Light Vehicles, and Infantry.',
			extra: 'Good vs. Infantry, Light Vehicles'
		},
		242: {
			name: 'Panther',
			help: "The Panther is one of the best Tanks in the war. Armed with a deadly 75mm main Gun and exceptional frontal armor, the Panther's only weakness is its rear and top armor.",
			extra: 'Good vs. Tanks'
		},
		243: {
			name: 'Panzer IV',
			help: 'The mainstay of the Panzer divisions, the Panzer IV is capable of tackling Enemy Tanks at range. Veteran Panzers are equipped with armor skirts and a MG42.',
			extra: 'Good vs. Infantry, Tanks'
		},
		244: {
			name: 'Sdkfz 234 Armored Car',
			help: 'A fast-moving reconnaissance Vehicle.  Pumas are equipped with a 50mm Anti Tank Gun.',
			extra: 'Good vs. Infantry'
		},
		251: {
			name: 'Stug IV',
			help: 'The Stug IV is armed with a fixed 75mm main Gun. The Stug IV is effective at supporting Infantry and ambushing Enemy Tanks.',
			extra: 'Good vs. Infantry, Tanks'
		},
		289: {
			name: 'Panzer Grenadiers',
			help: 'Panzer Grenadiers are tough and versatile infantry, trained to work with support vehicles in fast, mobile attacks.',
			extra: 'Good in large numbers'
		},
		292: {
			name: 'Assault Grenadier Heavy Infantry',
			help: 'These Panzer Elite Heavy Infantry are trained and equipped for Assault tactics. They come equipped with MP44 Sturmgewehr assault rifles.',
			extra: 'Good vs. Infantry'
		},
		293: {
			name: 'Tank Buster Heavy Infantry',
			help: 'Tank Buster Heavy Infantry are equipped with Panzerschreck Anti Tank weapons for handling armor threats.',
			extra: 'Good vs. Tanks'
		},
		295: {
			name: 'Scout Car',
			help: 'The SdKfz 221 Scout Car has great speed and mobility. Armed with an MG42 light machine gun, the Scout car can engage light targets and also capture and hold territory.',
			extra: 'Good vs. Snipers, can capture Territory'
		},
		296: {
			name: 'Armored Car',
			help: 'The Sdkfz 222 Armored Car marries high speed and all terrain mobility with a rapid firing 20mm cannon capable of destroying infantry and other soft targets.',
			extra: 'Good vs. Infantry'
		},
		298: {
			name: 'Infantry Halftrack',
			help: 'The SdKfz 250 is a small, light halftrack capable of carrying squads of infantry into an attack. The Infantry Halftrack can also supply the reinforcement needs of nearby troops.',
			extra: 'Good vs. Infantry, can reinforce nearby squads'
		},
		299: {
			name: 'Mortar Halftrack',
			help: 'Mortar Halftracks mount the heavy 81mm Granatewerfer 34 in the rear of the vehicle, enabling crews to fire the mortar with good protection from small arms fire.',
			extra: 'Good vs. Infantry'
		},
		300: {
			name: 'Light AT Halftrack',
			help: 'The Light AT Halftrack mounts a small, but accurate 37mm  Anti Tank gun in place of the normal machine gun. This halftrack can use its accuracy to hit infantry, and specifically target the running gear of tanks and other vehicles in order to disable them.',
			extra: 'Good vs. Light Tanks'
		},
		301: {
			name: "Funkwagen 'Vampire' Halftrack",
			help: "Powerful radios equip the 250/3 Funkwagen 'Vampire' enabling it to interdict enemy signals and disrupt their supply lines. This vehicle siphons resources away from enemy sectors that it sets up in.  It has no weaponry of its own, so must be supported when in enemy territory.",
			extra: 'Good for stealing enemy resources'
		},
		302: {
			name: 'Munitions Halftrack',
			help: 'The Munitions Halftrack is specially equipped to deliver munitions to front line units. Infantry and vehicles within the support radius of the Munitions Halftrack will rapidly recharge any abilities that make use of munitions.',
			extra: 'Lowers recharge on abilities'
		},
		305: {
			name: 'Bergetiger Repair and Recovery Vehicle',
			help: 'A heavy-lift crane and reconfigured turret turn this Tiger chassis into a Bergetiger, enabling it to repair tanks and other vehicles, and recover destroyed vehicles so they can be returned to action.',
			extra: 'Recovers destroyed vehicles'
		},
		313: {
			name: 'Hotchkiss Light Tank',
			help: 'The Hotchkiss is a lightly armored Tank with high mobility. Upgrading the Hotchkiss with a Stuka Rocket rack gives it mobile artillery capabilities.',
			extra: 'Area of Effect Barrage. Good vs. Infantry'
		},
		316: {
			name: 'Marder III Tank Hunter',
			help: 'The Marder III mounts a powerful Pak40 75mm Anti Tank gun on a 38t chassis but its drawbacks include a limited weapon traverse and poor crew protection.',
			extra: 'Good vs. tanks'
		},
		318: {
			name: 'Schwimmwagen Type 128',
			help: 'The unarmed Schwimmwagen Type 128 is highly versatile with the potential to track enemy targets, scorch strategic points, or lay mines.',
			extra: 'Detector unit. Captures Territory'
		},
		320: {
			name: 'Panzer IV Infantry Support Tank',
			help: 'This Panzer IV is equipped with a short-barreled, low velocity 75mm gun effective against soft targets, but terrible against even reasonable armor.',
			extra: 'Good vs. Infantry'
		},
		321: {
			name: 'Kettenkrad',
			help: 'This unarmed Kettenkrad halftrack is fast enough to provide reconnaissance, and can detect mines and enemy snipers.',
			extra: 'Detector unit. Captures Territory'
		}
	},
	upgrade: {
		3: { name: 'Paratroopers', help: 'Deploy Paratroopers on Revealed Territory.' },
		4: { name: 'Paradrop AT Gun', help: 'Deploy Paradropped 57mm Anti Tank Weapon and Crew.' },
		5: {
			name: 'Supply Drops',
			help: 'Paradrop Munitions, Fuel Supplies, and some Heavy Weapons to Revealed Territory.'
		},
		6: { name: 'Air Recon', help: 'Call in Recon Plane to scout targeted area of battlefield.' },
		7: { name: 'Strafing Run', help: 'Call in P47 Thunderbolt strafing run.' },
		8: { name: 'Bomber Run', help: 'Call in P47 Thunderbolt bombing run.' },
		10: { name: 'Raid', help: 'Light Vehicles can now capture Territory Sectors.' },
		11: {
			name: 'Calliope Rocket Launcher',
			help: 'Deploy an M4 Sherman outfitted with a Calliope T34 Rocket Launcher to the battlefield.'
		},
		12: {
			name: 'M26 Pershing Heavy Tank',
			help: 'Deploy an M26 Pershing Heavy Tank to the battlefield.'
		},
		13: { name: 'Fast Deployment', help: 'Vehicle and Tank production times are reduced.' },
		14: {
			name: 'Field Repairs',
			help: 'Vehicle Crews Repair battle damage while ability is active.'
		},
		15: {
			name: 'Allied War Machine',
			help: 'Tank losses are immediately replaced at the HQ while this ability is active.'
		},
		18: {
			name: 'Rapid Response',
			help: 'Infantry and Heavy Weapon Team deployment times are reduced.'
		},
		19: {
			name: 'Rangers',
			help: 'Rangers lead the way! Deploy Rangers, heavy Anti Tank Infantry, to the battlefield.'
		},
		20: {
			name: 'Off-Map Combat Group',
			help: 'Call Off-Map Infantry and Vehicle Reinforcements to the battlefield.'
		},
		21: {
			name: 'Defensive Operations',
			help: 'Enables Riflemen to Construct Field Defenses. Speeds up Engineer construction of Defenses.'
		},
		22: {
			name: 'Off-Map Artillery Support',
			help: 'Call in Artillery strike on designated target area.'
		},
		23: {
			name: '105mm Howitzer',
			help: 'Enables Engineers to deploy the 105mm Howitzer to the battlefield.'
		},
		24: {
			name: 'Level 1 Production',
			help: 'Decreases the upkeep cost of your troops and slightly increases the rate at which Riflemen Squads gain veterancy.'
		},
		25: {
			name: 'Level 2 Production',
			help: 'Greatly decrease the upkeep cost of your troops and slightly increase the rate at which Riflemen Squads gain veterancy.'
		},
		27: {
			name: 'M1A1C 76mm Gun',
			help: 'M4 Shermans are upgraded with the more powerful M1A1C 76mm gun. The weapon trades area effect high explosive for increased armor penetration. Researching this upgrade will also greatly increase the M26 Pershing’s chance to penetrate enemy armor.',
			extra: 'Better vs. Armor and Vehicles.'
		},
		31: {
			name: 'Demolitions',
			help: 'Equip Engineers with Demolition Explosives to take down Buildings and Bridges',
			extra: 'Lay traps for Enemy Units.'
		},
		32: {
			name: 'Mk2 Grenades',
			help: "Equip Riflemen Squads with the Mk2 'Pineapple' grenade for flushing Enemy infantry out of cover, or attacking garrisoned Buildings."
		},
		35: {
			name: 'Defensive Smoke Screen',
			help: "Equip your M4 Sherman's with Smoke Canisters to create Defensive Smoke Screens."
		},
		36: {
			name: 'Sticky bombs',
			help: 'Equip Riflemen with improvized Anti Tank weapons. Researching this upgrade will also increase the rate at which Riflemen Squads gain veterancy.',
			extra: 'Good vs. Vehicles and Tanks'
		},
		39: {
			name: 'Aid Station',
			help: 'Medics are deployed to the Aid Station and will recover Casualties from the battlefield and return them to active duty.'
		},
		43: {
			name: 'M2HB .50 cal Machine Gun',
			help: 'Equip the M18 Hellcat with a M2HB .50 cal Machine Gun.',
			extra: 'Better vs. Infantry'
		},
		46: {
			name: 'M2HB .50 cal Machine Gun',
			help: 'Equip the Armored Car with a M2HB .50 cal Machine Gun.',
			extra: 'Better vs. Infantry'
		},
		47: {
			name: 'M2HB .50 cal Machine Gun',
			help: 'Equip the Sherman with a M2HB .50 cal Machine Gun.',
			extra: 'Better vs. Infantry'
		},
		48: {
			name: 'M2HB .50 cal Machine Gun',
			help: 'Equip the Armored Car with a M2HB .50 cal Machine Gun.',
			extra: 'Better vs. Infantry'
		},
		49: {
			name: 'M2 Flamethrower',
			help: 'Equip Engineers with the M2 Flamethrower.',
			extra: 'Better vs. Infantry, Buildings.'
		},
		51: {
			name: 'Armor Skirts',
			help: 'Equip the Armored Car with Light Armor Skirts.',
			extra: 'Improved Armor'
		},
		52: {
			name: 'M18 57mm Recoilless Rifle',
			help: 'Equip Paratroopers with the M18 57mm AT Recoilless Rifle to provide an effective counter to Vehicles and hardened Structures.',
			extra: 'Good vs. Vehicles, Tanks.'
		},
		54: {
			name: 'Quad .50 cal Maxson Mount',
			help: 'Equip Halftrack with Quad .50 cal Maxson Mount. Cannot transport Troops when Equipped.',
			extra: 'Improve Anti Infantry effectiveness'
		},
		55: { name: 'Thompson SMG', help: 'Equip your Rangers with the Thompson SMG.' },
		59: { name: 'Bulldozer', help: "Equip your M4 'Crocodile' Sherman  with the Bulldozer." },
		61: {
			name: 'Crab Mine Flail',
			help: 'Equip the M4 Sherman with the Crab Mine Flail. Destroys Enemy Mines when deployed.',
			extra: 'Good vs. Mines, Infantry'
		},
		69: {
			name: 'Minesweeper',
			help: 'Equip Engineers with the SCR-625 Mine detector to clear mines.'
		},
		85: {
			name: 'M1918 Browning Automatic Rifle (BAR)',
			help: 'Equip all Riflemen Squads with the BAR. Squads equipped with the BAR can use the Suppression Fire ability. Researching this upgrade will also increase the rate at which Riflemen Squads gain veterancy.'
		},
		90: {
			name: 'Secured Resourcing',
			help: 'Territory secured by this Command Truck will generate bonus munitions or fuel. Only one Secured Resourcing upgrade may be active among all command trucks at one time.'
		},
		91: {
			name: 'Become Mobile',
			help: 'Order the Truck to Mobilize. A Mobile Truck cannot create units.'
		},
		95: { name: 'Lieutenant ( Available From Command HQ )' },
		96: {
			name: 'Speed Governors',
			help: 'Engine governors are removed through field modifications, providing a large speed increase for your mobile Headquarters vehicle.'
		},
		102: {
			name: 'Recon Element',
			help: 'Upgrades to a faster moving, but more lightly armed recon squad; also adds a well trained marksman and allows the squad to detect mines while stationary.',
			extra: 'Can utilize the Lee Enfield Sniper rifle'
		},
		103: {
			name: 'Convert to MMG Carrier',
			help: 'Adds Vickers Medium Machine gun to Bren Carrier to create a mobile machine gun. Cannot carry troops when upgraded.'
		},
		106: {
			name: 'Mine Plow',
			help: 'The mine plow enables Churchills to remove enemy minefields.'
		},
		111: {
			name: 'Bren Light Machine Gun',
			help: 'The Bren Light Machine Gun adds much needed firepower to the Infantry Section and also enables them to slow enemy vehicles with accurate fire.',
			extra: 'Better vs. Infantry and vehicles'
		},
		112: {
			name: 'Disposal and Detection Section',
			help: 'The Sapper squad specializes in mine detection and destroying obstacles with demolitions pack.',
			extra: 'Addition: Plant Demolition Charge ability, Minesweeper'
		},
		113: {
			name: 'Expert Engineers',
			help: 'The Sapper squad specializes in battlefield repair of vehicles and structures.',
			extra: 'Addition: Repair ability replaced by Over Repair'
		},
		114: {
			name: 'Sgt. Medical Expert',
			help: 'Promotes a member within the squad who is an ace with morphine',
			extra: 'Addition: Area of Effect heal ability'
		},
		115: {
			name: 'PIAT',
			help: 'Sappers are issued PIAT Anti Tank weapons. "PIAT" stands for Projector Infantry Anti Tank.',
			extra: 'Good vs. Vehicles, Tanks'
		},
		116: {
			name: 'Recon Element',
			help: 'Upgrades to a faster moving, but more lightly armed recon squad; also adds a well trained marksman and allows the squad to detect mines while stationary.',
			extra: 'Can utilize the Lee Enfield Sniper rifle'
		},
		117: {
			name: 'Rifle Grenades',
			help: 'The infantry section will upgrade their rifles to enable them to fire grenades.',
			extra: 'Good vs. Infantry and Infantry in Buildings'
		},
		118: {
			name: 'Tank Crew Commander',
			help: 'The tank crew commander will emerge to survey the battlefield, improving sight range.',
			extra: 'Tank Commander'
		},
		119: {
			name: 'Tank Crew Commander',
			help: 'The tank crew commander will emerge to survey the battlefield, improving sight range.',
			extra: 'Tank Commander'
		},
		120: {
			name: 'Littlejohn Adapter',
			help: 'Littlejohn Adapter increases projectile velocity and armor penetration of the 2 Pounder Gun.',
			extra: 'Triples armor penetration'
		},
		132: {
			name: 'MG42 Heavy Machine Gun',
			help: 'An MG42 Heavy Machine Gun is emplaced inside the Bunker. The weapon fires on a fixed arc to the front of the Bunker.'
		},
		133: {
			name: 'Repair Station',
			help: 'Upgrade this Bunker to a Repair Facility. Specially trained Pioneers will automatically Repair damaged Vehicles in the vicinity of the Bunker.'
		},
		141: {
			name: 'Flammenwerfer 42',
			help: 'Equip Pioneers with the Flammenwerfer 42 portable Flamethrower.',
			extra: 'Better vs. Infantry, Buildings.'
		},
		142: { name: 'Goliath', help: 'Purchase a Goliath Remote Bomb.' },
		143: {
			name: 'Flammenwerfers',
			help: 'Equip this Halftrack with two Flammenwerfers. Transport space is cut to manage the huge Fuel reservoir.',
			extra: 'Anti Infantry, Anti Building'
		},
		144: {
			name: 'Walking Stuka',
			help: "Equip this Halftrack with Wurfrahmen 40 Rockets. Known as the 'Walking Stuka' because of its distinctive sounds the Rockets made while firing.",
			extra: 'Area of Effect. Good vs. Infantry and Light Vehicles.'
		},
		146: {
			name: 'Puma 50mm Gun',
			help: 'Equip the SdKfz 234 Armored Car with a 50mm Anti Tank Gun turret.',
			extra: 'Better vs. Vehicles, Tanks.'
		},
		149: {
			name: 'MG42 Light Machine Gun',
			help: 'Equip Squad with MG42 Light Machine Gun. The addition of an MG42 Light Machine Gun to the Squad vastly improves their firepower, but at a slight reduction of mobility.',
			extra: 'Improved Anti Infantry effectiveness'
		},
		152: {
			name: 'Frankfurt 42 Mine Detector',
			help: 'Equip your Pioneers with the Frankfurt 42 Mine detector.'
		},
		153: {
			name: 'MP44 Sturmgewehr (Assault Rifles)',
			help: 'Equip Squad with MP44 Assault Rifles. MP44s provide Squads with excellent mid and short-range firepower.'
		},
		158: {
			name: 'Panzerfaust',
			help: 'Equip Squad with Panzerfaust. Panzerfausts are one-shot Anti-Vehicle weapons.'
		},
		159: {
			name: 'RPzB 54 Panzerschreck',
			help: 'Equip Squad with Panzerschreck. One of the deadliest Anti Tank weapons of the war, the RPzB 54 Panzerschreck could penetrate the armor of any Allied tank.',
			extra: 'Good vs. Tanks, Vehicles'
		},
		167: {
			name: 'MP40 Sub-Machine Gun',
			help: 'Volksgrenadier Squads get improved short-range firepower with the MP40 Sub-Machine Gun.',
			extra: 'Improved short range combat.'
		},
		170: {
			name: 'MG42 Light Machine Gun',
			help: 'Equip Squad with MG42 Light Machine Gun. The addition of an MG42 Light Machine Gun to the Squad vastly improves their firepower, but at a slight reduction of mobility.',
			extra: 'Improved Anti Infantry effectiveness'
		},
		171: {
			name: 'Escalate to Skirmish Phase',
			help: 'Requisition the Krieg Barracks to deploy Grenadier Squads, Mortar teams, Halftracks, and the Pak 38 Anti Tank Gun.'
		},
		172: {
			name: 'Escalate to Assault Phase',
			help: 'Requisition the Sturm Armory to deploy Officers, Stug Ivs., Geschutzwagens, SdKfz 234 Armored Cars, and the Nebelwerfer Rocket Battery.'
		},
		173: {
			name: 'Escalate to Battle Phase',
			help: 'Requisition Panzer Command to deploy the Knights Cross Holder, Ostwind Flak Panzer, Panzer IV, and the Panther Heavy Tank.'
		},
		174: {
			name: 'Veteran Infantry Squads',
			help: 'Requisition Veteran Infantry Squads. Call in Eastern Front Veteran Volksgrenadiers, Grenadiers, Stormtrooper, Knights Cross Holders, and Officers.',
			extra: 'Veteran Troops'
		},
		175: {
			name: 'Crack Infantry',
			help: 'Infantry are trained to Crack level.',
			extra: 'Crack Troops with combat experience'
		},
		176: {
			name: 'Elite Infantry',
			help: 'Infantry reach Elite status.',
			extra: 'Elite Troops hardened in combat.'
		},
		177: {
			name: 'Veteran Support Units',
			help: 'Requisition Veteran Support Units. Includes  HMG and Mortar sections, Snipers, Pioneers, and Nebelwerfers.',
			extra: 'Veteran Support Units'
		},
		178: {
			name: 'Crack Support Units',
			help: 'Upgrade your support Squads to level 2 Veterancy.',
			extra: 'Crack Support Units'
		},
		179: {
			name: 'Elite Support Units',
			help: 'Support Units reach Elite status with lots of combat experience.',
			extra: 'Elite Support Units'
		},
		180: {
			name: 'Veteran Tanks',
			help: 'Requisition Veteran Tank Crews. Tanks include the Stug, StuH, Ostwind Flakpanzer, Panzer IV, Panthers, and Tigers.',
			extra: 'Veteran Tank Crew'
		},
		181: {
			name: 'Crack Tank Crew',
			help: 'Crack tank Crews have lots of combat experience and operate at a high level of proficiency.',
			extra: 'Crack Tank Crews'
		},
		182: {
			name: 'Elite Tanks',
			help: 'Elite Tank Crews have abundant combat experience.',
			extra: 'Elite Tank Crews'
		},
		183: {
			name: 'Veteran Vehicles',
			help: 'Requisition Veteran Vehicles. Vehicles include Motorcycles, Schwimmwagens, Halftracks, Pumas, 50mm Pak38 AT Guns, and 88mm Flak 36s.',
			extra: 'Veteran Vehicles'
		},
		184: {
			name: 'Crack Vehicles',
			help: 'Combat experience leads to Crack status.',
			extra: 'Crack Vehicles'
		},
		185: {
			name: 'Elite Vehicles',
			help: 'Elite vehicle Crews have years of combat experience.',
			extra: 'Elite Vehicle Crews'
		},
		187: {
			name: 'Infantry Assault Team',
			help: 'Call Off-Map Stormtrooper Reinforcements to the battlefield. Ideal for general battlefield actions.'
		},
		188: {
			name: 'Urban Assault Support',
			help: 'Call an Off-Map Stuh 42 assault howitzer to the battlefield. Ideal for urban assault operations.'
		},
		189: {
			name: 'Armored Assault Force',
			help: 'Call an Off-Map Tiger Tank Reinforcement to the battlefield. Ideal for major assault operations.'
		},
		190: {
			name: 'Assault Grenadiers',
			help: 'Enables Infantry Squads to Assault targets with Grenades.'
		},
		191: {
			name: 'Blitzkrieg Assault!',
			help: 'Enables all Vehicles and Infantry to attack with overwhelming speed while this ability is active.'
		},
		192: {
			name: 'Resource Blitz',
			help: 'Receive a large Manpower bonus in exchange for freezing your Economy for a short period of time.'
		},
		195: {
			name: 'For the Fatherland!',
			help: 'Zealous patriotism gives all friendly Units in controlled Territory a defensive bonus.'
		},
		196: {
			name: 'Fortify the Perimeter',
			help: 'Upgrades all Base Buildings with Defensive Machine Guns. Enables Reinforcement around Bunkers.'
		},
		197: {
			name: '88mm Flak 36 AT/AA',
			help: 'Enables Pioneers to deploy the 88mm Flak 36 AA/AT to the battlefield.'
		},
		198: {
			name: 'Advanced Warning',
			help: 'Increases the visual range of all captured Points, revealing more of the surrounding Territory.'
		},
		199: {
			name: 'Registered Artillery',
			help: 'Call Off-Map Defensive Artillery Bombardment on one of your threatened Structures or Secured Points.'
		},
		200: {
			name: 'Rocket Artillery',
			help: 'Call Off-Map Barrage of devestating 280mm Rockets to target area.'
		},
		203: {
			name: 'Activate Panther Battlegroup',
			help: 'Enables two Panther tanks to be allocated to support offensive operations.'
		},
		210: {
			name: 'Artillerie Kommand',
			help: 'Panzer Grenadier Bonus: Unlocks the Panzerschreck upgrade',
			extra:
				'Can Construct: Light AT halftrack, Bergetiger Recovery Vehicle, Panzer IV Infantry Support Tank'
		},
		211: {
			name: 'Support Kommand Upgrade',
			help: 'Enables the construction of heavy support vehicles.',
			extra: 'Makes available: Panzer IV Infantry Support Tank and Hotchkiss Light Tank'
		},
		212: {
			name: 'Jager Kommand',
			help: 'Panzer Grenadier Bonus: Unlocks the MP44 Upgrade',
			extra: "Can Construct: Assault Grenadiers, Funkwagen 250/5 'Vampire', Marder III Tank Hunter"
		},
		213: {
			name: 'Jager Kommand Upgrade',
			help: 'The Jager Kommand can produce the Marder III Tank Hunter.',
			extra: 'Makes available: Marder III Tank Hunter'
		},
		214: {
			name: 'Logistik Upgrade',
			help: 'Upgrade this Scout Car with the ability to lock down and secure the targeted territory sector.'
		},
		215: {
			name: 'FG42 Assault Rifle',
			help: 'Equip Fallschirmjager with FG42 Assault Rifles for increased firepower.'
		},
		216: {
			name: 'Spotting Scope',
			help: 'The Spotting Scope increases sight and gun range of the Hetzer Tank Destroyer.'
		},
		218: {
			name: 'Long-barreled 37mm Cannon',
			help: 'Upgrade the Hotchkiss Main Turret to a long-barreled 37mm SA 18 gun utilizing armor piercing rounds.'
		},
		219: {
			name: 'Walking Stuka',
			help: "Equip this Hotchkiss with Wurfrahmen 40 Rockets. Known as the 'Walking Stuka' because of its distinctive sounds the Rockets made while firing.",
			extra: 'Area of Effect. Good vs. Infantry and Light Vehicles.'
		},
		221: {
			name: 'Armor Skirts',
			help: "Equips the Panzer IV with Armored 'Skurzen' that can lessen the impact of high explosive and shaped-charge rounds."
		},
		222: {
			name: 'MG42 gunner',
			help: 'Upgrades the Panzer IV with an MG42 gunner.',
			extra: 'Good vs. Infantry'
		},
		226: {
			name: 'Panzerschreck',
			help: 'Equip your Panzer Elite squad with an armor destroying Panzerschreck.',
			extra: 'Good vs. Vehicles and Tanks'
		},
		227: {
			name: 'Panzerschreck',
			help: 'Equip your Panzer Elite squad with an armor destroying Panzerschreck.',
			extra: 'Good vs. Vehicles and Tanks'
		},
		228: {
			name: 'Gewehr 43 Package',
			help: 'Equip your Panzer Elite squad with two Gewehr 43 Rifles, excellent at long-range combat.'
		},
		229: {
			name: 'MP44 Sturmgewehr (Assault Rifles)',
			help: 'Equip your Panzer Infantry squad with MP44 Assault Rifles that provide excellent mid and short-range firepower.'
		},
		240: {
			name: 'Kampfgruppe Kompanie',
			help: 'Panzer Grenadier Bonus: Upgrades Grenadier repair to Advanced Repair',
			extra: 'Can Construct: Light AT Halftrack (250/10), Mortar Halftrack (250/7), Halftrack (250)'
		},
		241: {
			name: 'Kampfgruppe Kompanie Upgrade',
			help: 'Allows Grenadier Tank Buster squads to be built and unlocks the panzerschreck upgrade on Panzer Grenadier squads.',
			extra: 'Makes available: Tank Buster squads'
		},
		243: {
			name: 'Logistik Kompanie Upgrade',
			help: 'Allows Grenadier Tank Buster squads to be built and unlocks the panzerschreck upgrade on Grenadier squads.',
			extra: 'Makes available: Light Armored Car (SdKfz 222)'
		},
		244: {
			name: 'Advanced Repair',
			help: 'Upgrade the repair rate of your Panzer Grenadiers, Assault Grenadiers, and Tank Busters.'
		},
		245: {
			name: 'Anti Tank Grenades',
			help: 'Enables Anti Tank Grenades on your Panzer Grenadier, Assault Grenadier, and Tank Buster squads.'
		},
		246: {
			name: 'Field Craft',
			help: 'Increase the Capture Rate of your Panzer Grenadier, Assault Grenadier, and Tank Buster squads. When static, these squads are also trained to spot enemy mines.'
		},
		247: {
			name: 'Incendiary Grenades',
			help: 'Enables most Panzer Infantry with Incendiary Grenades that will burn an area for a period of time.',
			extra: 'Good vs. Garrisoned Infantry and Infantry'
		},
		248: {
			name: 'Group Zeal',
			help: 'Panzer Grenadiers, Assault Grenadiers, and Tank Busters are tougher when grouped together.'
		},
		249: {
			name: 'Defensive Operations',
			help: 'Upgrade your HQ Territory to recharge all Panzer Elite abilities and heal any injured infantry units. Will also heal units near Reinforcement Points.'
		},
		250: { name: 'Sprint Ability' },
		251: {
			name: 'Increase Squad Sizes',
			help: 'Increase Panzer Grenadier, Assault Grenadier, and Tank Buster squad sizes.'
		},
		252: {
			name: 'Veteran Sergeant',
			help: 'Upgrade your Panzer Grenadier, Assault Grenadier, and Tank Buster squads with a Veteran Sergeant who increases the rate squads receive veterancy and reduces the amount of suppression they receive.'
		},
		253: { name: 'Defensive Bonus 1', help: 'Gain a Defensive Veterancy Bonus.' },
		254: { name: 'Defensive Bonus 2', help: 'Gain a Defensive Veterancy Bonus.' },
		255: { name: 'Defensive Bonus 3', help: 'Gain a Defensive Veterancy Bonus.' },
		256: { name: 'Offensive Bonus 1', help: 'Gain an Offensive Veterancy Bonus.' },
		257: { name: 'Offensive Bonus 2', help: 'Gain an Offensive Veterancy Bonus.' },
		258: { name: 'Offensive Bonus 3', help: 'Gain an Offensive Veterancy Bonus.' },
		259: {
			name: 'Defensive Bonus',
			help: 'Give this squad a Defensive Veterancy Bonus, improving survivability and speed.'
		},
		260: {
			name: 'Defensive Bonus 2',
			help: 'Give this squad a Defensive Veterancy Bonus, improving survivability and speed.'
		},
		261: {
			name: 'Defensive Bonus 3',
			help: 'Give this squad a Defensive Veterancy Bonus, improving survivability and speed.'
		},
		262: {
			name: 'Offensive Bonus',
			help: 'Give this squad an Offensive Veterancy Bonus, improving weapon accuracy and rate of fire.'
		},
		263: {
			name: 'Offensive Bonus 2',
			help: 'Give this squad an Offensive Veterancy Bonus, improving weapon accuracy and rate of fire.'
		},
		264: {
			name: 'Offensive Bonus 3',
			help: 'Give this squad an Offensive Veterancy Bonus, improving weapon accuracy and rate of fire.'
		},
		266: {
			name: 'Zeal',
			help: 'Fanaticism causes Infantry Squads to fight more fiercely as they take losses.'
		},
		267: {
			name: 'Propaganda War',
			help: 'Superior Propaganda efforts demoralize Enemy Troops forcing a retreat to their HQ area.'
		},
		268: {
			name: 'King Tiger',
			help: 'A single, very powerful King Tiger is allocated to the battlefield, but only once. Such a decisive weapon should not be squandered.'
		},
		269: {
			name: 'Inspired Assault',
			help: 'Propaganda efforts inspire all Troops to attack the Enemy with renewed intensity with no regard for their personal safety while this ability is active.'
		},
		270: {
			name: 'Firestorm',
			help: 'Call Off-Map Bombardment to target an area. All Enemy Troops will be caught in a Firestorm.'
		},
		271: { name: 'V1 Rocket Attack', help: 'Call the terrifying V1 Rocket down on targeted area.' },
		273: { name: 'Upgrade to Barracks', help: 'Produce Troops from this Structure.' },
		274: {
			name: 'Upgrade to Reinforce Point',
			help: 'Upgrade this structure to reinforce nearby troops. Upgrading Defensive Operations at the HQ will allow passive healing of infantry at the Reinforce Point.'
		},
		296: {
			name: 'Fallschirmjager Infiltration',
			help: 'Fallschirmjager squads can be ordered to reveal themselves from pre-infiltrated hiding locations in buildings. Fallschirmjager squads camouflage automatically when in heavy cover.'
		},
		297: {
			name: 'Butterfly Bombs',
			help: 'Low flying aircraft can drop fields of SD-2 Butterfly bombs to disrupt the movement of enemy infantry and light vehicles.'
		},
		298: {
			name: 'Henschel Combat Air Patrol',
			help: 'Henschel Hs. 129 ground attack aircraft will provide tactical air-cover with their powerful 75mm cannons. Aircraft will monitor targeted locations for enemy vehicles or tanks.',
			extra: 'Good vs. Tanks'
		},
		299: {
			name: 'Luftwaffe Ground Forces',
			help: 'Luftwaffe ground forces are adequate soldiers who can construct light defenses and, more importantly, devastating AA weapons including the Flakvierling  quad 20mm cannon.'
		},
		300: {
			name: 'Wirblewind Flakpanzer',
			help: 'Order a dangerous Wirblewind Flakpanzer that can provide mobile AA coverage, or engage enemy infantry and light vehicles.'
		},
		301: {
			name: 'Flak 36 88mm Cannon',
			help: 'Luftwaffe Ground Forces  are able to construct the fearsome 88mm Flak 36, a dual role weapon capable of targeting both air and ground units at long ranges.'
		},
		303: {
			name: 'Booby Trap Building',
			help: 'Panzer Elite infantry can be ordered to plant deadly booby traps inside any building on the map. Enemy infantry entering the building will suffer extreme consequences.'
		},
		304: {
			name: 'Booby Trap Strategic Point',
			help: 'Panzer Elite infantry can be ordered to booby trap any strategic point in the game. Booby traps are triggered by enemy units attempting to capture the point.',
			extra: 'Booby Trap'
		},
		305: {
			name: 'Sector Artillery',
			help: 'A selected sector is monitored for enemy activity. When enemy units are detected, the area is  saturated with artillery until that enemy activity ceases.',
			extra: 'Sector Artillery'
		},
		306: {
			name: 'Roadblocks',
			help: 'Massive roadblocks are built that cannot be crushed by any unit, forcing the enemy to direct combat resources to destroying the barricades.'
		},
		307: {
			name: 'Scorched Earth',
			help: 'Following the ancient doctrine of scorched earth, Strategic Points can be disabled, denying their use to the enemy.',
			extra: 'Scorched Earth'
		},
		308: {
			name: 'Hummel Self-Propelled Artillery',
			help: 'A Hummel Self-Propelled 150mm howitzer can devastate large swaths of ground at long range with its massive shells.',
			extra: 'Hummel Self-Propelled Artillery'
		},
		310: {
			name: 'Teller Mines',
			help: 'Panzer Elite infantry can deploy Teller Mines. These weapons require great mass to trigger, meaning only vehicles will cause the mine to explode.'
		},
		311: {
			name: 'Hetzer Tank',
			help: 'A Hetzer Tank Hunter is available for reinforcement. These maneuverable tanks have thick sloping armor, and their small size means they are easily camouflaged.'
		},
		312: {
			name: 'Double Infantry AT Efforts',
			help: 'Panzerschreck upgrades now provide two Panzerschrecks, and AT grenade abilities now throw two AT Grenades.'
		},
		313: {
			name: 'Tank Awareness',
			help: 'Panzer Elite infantry use their improved battlefield skills to detect enemy tanks at ranges beyond which they can see.'
		},
		314: {
			name: 'APCR Rounds',
			help: 'AT guns and main tank guns are issued the more powerful APCR (Armor Piercing Composite Rigid) Panzergranate 40 ammunition that will improve armor penetration.'
		},
		315: {
			name: 'Jagdpanther Tank Destroyer',
			help: 'A  very rare and powerful Jagdpanther is allocated only once to each commander. Extremely well armed and armored, the Jagdpanther is capable of tackling all enemy units.'
		},
		317: {
			name: 'Forward Observation Officers',
			help: 'Allows Lieutenants and Captains to call in off-map artillery barrages, and the Command Tank can drop smoke to create cover.'
		},
		318: {
			name: 'Creeping Barrage',
			help: 'Howitzers and Priests can fire a series of shells in rapid succession creating a path of destruction.',
			extra: 'Creeping Barrage'
		},
		319: {
			name: 'Priest 105mm SPG',
			help: 'A 105mm Howitzer mounted on a lightly Armored Sherman chassis provides mobile fire support.',
			extra: 'Priest 105mm'
		},
		320: {
			name: 'Supercharge Artillery Rounds',
			help: '25 Pounders, Priests, and mortar emplacements get supercharged shell propellant bags for vastly increased weapon range.',
			extra: 'Supercharge Artillery Rounds'
		},
		321: {
			name: 'Overwatch Artillery',
			help: '25 Pounders, Priests, and Mortar Emplacements can be set to watch an area for incoming units and barrage them with artillery fire.',
			extra: 'Overwatch Artillery'
		},
		322: {
			name: 'Counter Battery',
			help: 'Enables 25 Pounder and Mortar Emplacements to be toggled into Counter Battery, where they will fire back at enemy artillery automatically.',
			extra: 'Counter Battery'
		},
		324: {
			name: 'Glider-borne  Commandos',
			help: 'Call in a section of elite, Glider-borne Commandos.'
		},
		325: {
			name: 'Tetrarch Tank',
			help: 'A heavy Hamilcar glider can deliver a Tetrarch light tank armed with a 2 Pounder gun.'
		},
		326: {
			name: 'Glider Headquarters',
			help: 'Call in a glider Headquarters that can produce Commando Mortar sections, Command Vickers HMG Teams, and PIAT armed tank hunting teams.'
		},
		327: {
			name: 'Radio Triangulation Detectors',
			help: 'Infantry units can place Radio Triangulation Detectors to track the movement of enemy units.'
		},
		328: {
			name: 'Ultra Decryption',
			help: 'Secret intelligence generated through Ultra Decryption enables British players access to enemy orders.'
		},
		329: {
			name: 'Decoy Artillery',
			help: 'Grants decoy and artillery barrages. Use them in combination to keep your opponent guessing.'
		},
		331: {
			name: 'Improved Emplacements',
			help: 'Royal Engineers use their knowledge of fortifications to reinforce all weapon emplacements to make them more resistant to damage.'
		},
		332: {
			name: 'Hull Down',
			help: 'British Tanks are able to improve their defensive capabilities at the cost of mobility.',
			extra: 'Hull Down Tactics'
		},
		333: {
			name: 'Improved Command Vehicles',
			help: 'Command HQs, Field Support Trucks, and Armored Command Trucks can move more quickly, increase population cap, take less damage, and generate more resources.',
			extra: 'Improved Mobile Trucks'
		},
		334: {
			name: 'Churchill Infantry Tank',
			help: 'The lightly armed, but heavily Armored Churchill Tank will support Royal Engineer operations and can also be equipped with a mine plow.',
			extra: 'Churchill Infantry Tank'
		},
		335: {
			name: 'Churchill AVRE',
			help: 'The Churchill AVRE can use its devastating Petard Mortar to smash through enemy obstacles.',
			extra: 'Churchill AVRE'
		},
		336: {
			name: 'Churchill Crocodile',
			help: 'The Churchill Crocodile wields a 6 Pounder gun and a fearsome flame projector.',
			extra: 'Churchill Crocodile'
		}
	}
};
