services:
  pocketbase:
    image: ghcr.io/company-of-heroes/app/pocketbase
    ports:
      - '${PB_PORT:-8090}:${PB_PORT:-8090}'
    volumes:
      - pocketbase_data:/pb_data
      - pocketbase_hooks:/pb_hooks
      - pocketbase_migrations:/pb_migrations
    environment:
      - PB_PORT=${PB_PORT:-8090}
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
    restart: unless-stopped
volumes:
  pocketbase_data:
  pocketbase_hooks:
  pocketbase_migrations:
