import maps from '../data/maps.json';

/**
 * Steam Workshop maps, generated by `company-of-heroes-assets/tools/extract_maps.py` from the
 * Relaunch subscriptions folders. `key` is the scenario file name, the same string the app
 * stores as a lobby's map; the preview image is `<key>_map_base.webp` next to the stock map images.
 */
export type WorkshopMap = {
	key: string;
	name: string;
	players: number | null;
	workshopId: string | null;
	hasImage: boolean;
};

export const WORKSHOP_MAPS: WorkshopMap[] = maps;

const byKey = new Map(WORKSHOP_MAPS.map((map) => [map.key, map]));

export const workshopMap = (key: string): WorkshopMap | undefined => byKey.get(key.toLowerCase());
