import type { DocByRange, DocCost, DocModifier, DocVeterancyRank } from './types';

/** Headline numbers of a weapon; the full tables are in `weapons.json` (docs pages). */
export type ReplayWeapon = {
	name: string;
	damage?: { min: number | null; max: number | null };
	range?: number;
	/** Upper distance of the short / medium / long bands. */
	bands?: DocByRange;
	accuracy?: DocByRange;
	penetration?: DocByRange;
	cooldown?: { min: number | null; max: number | null };
	areaRadius?: number;
};

export type ReplayUnitStats = {
	/** Wiki slug (`/wiki/units/<slug>`). */
	slug?: string;
	/** Only obtainable through this doctrine call-in, at this cost (not the squad's production cost). */
	callIn?: { name: string; cost: DocCost };
	size?: number;
	/** Health of one model (the sturdiest). */
	health?: number;
	weapons?: string[];
	/** Ranks with their bonuses (only squads that earn veterancy themselves). */
	veterancy?: DocVeterancyRank[];
	/** Panzer Elite: veterancy bought per rank, an offensive or a defensive bonus (upgrade ids by rank). */
	vetUpgrades?: { offensive?: number[]; defensive?: number[] };
};

export type ReplayUpgradeStats = {
	effects?: DocModifier[];
	/** Weapons of the slot items it adds. */
	weapons?: string[];
	/** Names of the abilities it unlocks. */
	abilities?: string[];
};

/** Game stats keyed by replay objectId (`sbps`, `upgrade`), generated by `extract_docs.py`. */
export type ReplayStats = {
	/** Doctrine pick (lock upgrade id) → wiki slug of its commander. */
	commanders: Record<string, string>;
	/** Doctrine pick (lock upgrade id) → its two branches as unlock upgrade ids, top to bottom. */
	doctrines: Record<string, number[][]>;
	sbps: Record<string, ReplayUnitStats>;
	upgrade: Record<string, ReplayUpgradeStats>;
	weapons: Record<string, ReplayWeapon>;
};

let loading: Promise<ReplayStats> | undefined;

/** Lazily imports the compact table (~60 KB), once. */
export function loadReplayStats(): Promise<ReplayStats> {
	loading ??= import('../data/replay.json').then((module) => module.default as ReplayStats);
	return loading;
}
