<script lang="ts">
	import * as Form from '$lib/components/ui/form';
	import { Button } from '$lib/components/ui/button';
	import { FileSelection } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import { app } from '$core/app';
	import { H } from '$lib/components/ui/h';
	import ImportIcon from 'phosphor-svelte/lib/DownloadSimple';
	import ExportIcon from 'phosphor-svelte/lib/Export';
</script>

<H level="1">Settings</H>
<Form.Root>
	<Form.Group>
		<Label>Company of Heroes warnings.log</Label>
		<Form.Description>
			Select the warnings.log file generated by Company of Heroes.
		</Form.Description>
		<FileSelection
			name="pathToConfig"
			bind:value={app.settings.companyOfHeroesConfigPath}
			filters={[{ name: 'warnings.log', extensions: ['log'] }]}
		/>
	</Form.Group>
	<Form.Group>
		<Label>Company of Heroes installation folder</Label>
		<Form.Description>Select the root installation folder of Company of Heroes.</Form.Description>
		<FileSelection
			name="pathToInstallation"
			directory
			bind:value={app.settings.companyOfHeroesInstallationPath}
		/>
	</Form.Group>
	<H level="4">Import / Export</H>
	<Form.Group>
		<Label>Import configuration</Label>
		<Form.Description>
			Import a configuration JSON file to restore your settings. This will overwrite your current
			configuration.
		</Form.Description>
		<Button variant="secondary" type="button" class="w-fit" onclick={() => app.importSettings()}>
			<ImportIcon />
			Import
		</Button>
	</Form.Group>
	<Form.Group>
		<Label>Export configuration</Label>
		<Form.Description>
			Export your current configuration to a JSON file. You can then import it later to restore your
			configuration.
		</Form.Description>
		<Button variant="secondary" type="button" class="w-fit" onclick={() => app.exportSettings()}>
			<ExportIcon />
			Export
		</Button>
	</Form.Group>
</Form.Root>
