/// <reference path="../pb_data/types.d.ts" />

// 1v1 tournaments: staff create them, users sign up, the bracket lives in `tournament_matches`.
// Everything is written by the website (superuser); drafts are only visible to staff.
// Match scores are filled from finished lobbies by the website's `tournament-sync` job.
// `tournament_maps` holds staff-made maps (name + icon) for map pools; built-in maps need no record.
const STAFF = '@request.auth.role = "admin" || @request.auth.role = "moderator"';

const id = (collection) => ({
	autogeneratePattern: '[a-z0-9]{15}',
	hidden: false,
	id: `text_${collection}_id`,
	max: 15,
	min: 15,
	name: 'id',
	pattern: '^[a-z0-9]+$',
	presentable: false,
	primaryKey: true,
	required: true,
	system: true,
	type: 'text'
});

const text = (collection, name, max, required = false) => ({
	autogeneratePattern: '',
	hidden: false,
	id: `text_${collection}_${name}`,
	max,
	min: 0,
	name,
	pattern: '',
	presentable: name === 'name' || name === 'alias',
	primaryKey: false,
	required,
	system: false,
	type: 'text'
});

const number = (collection, name, required = false) => ({
	hidden: false,
	id: `number_${collection}_${name}`,
	max: null,
	min: null,
	name,
	onlyInt: true,
	presentable: false,
	required,
	system: false,
	type: 'number'
});

const select = (collection, name, values) => ({
	hidden: false,
	id: `select_${collection}_${name}`,
	maxSelect: 1,
	name,
	presentable: false,
	required: true,
	system: false,
	type: 'select',
	values
});

const relation = (collection, name, collectionId, cascadeDelete = false, required = false) => ({
	cascadeDelete,
	collectionId,
	hidden: false,
	id: `relation_${collection}_${name}`,
	maxSelect: 1,
	minSelect: 0,
	name,
	presentable: false,
	required,
	system: false,
	type: 'relation'
});

const date = (collection, name) => ({
	hidden: false,
	id: `date_${collection}_${name}`,
	max: '',
	min: '',
	name,
	presentable: false,
	required: false,
	system: false,
	type: 'date'
});

const bool = (collection, name) => ({
	hidden: false,
	id: `bool_${collection}_${name}`,
	name,
	presentable: false,
	required: false,
	system: false,
	type: 'bool'
});

const json = (collection, name) => ({
	hidden: false,
	id: `json_${collection}_${name}`,
	maxSize: 0,
	name,
	presentable: false,
	required: false,
	system: false,
	type: 'json'
});

/** Public image; `thumbs` are generated by PocketBase on request (`?thumb=`). */
const image = (collection, name, maxSize, thumbs) => ({
	hidden: false,
	id: `file_${collection}_${name}`,
	maxSelect: 1,
	maxSize,
	mimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
	name,
	presentable: false,
	protected: false,
	required: false,
	system: false,
	thumbs,
	type: 'file'
});

const autodates = (collection) => [
	{
		hidden: false,
		id: `autodate_${collection}_created`,
		name: 'created',
		onCreate: true,
		onUpdate: false,
		presentable: false,
		system: false,
		type: 'autodate'
	},
	{
		hidden: false,
		id: `autodate_${collection}_updated`,
		name: 'updated',
		onCreate: true,
		onUpdate: true,
		presentable: false,
		system: false,
		type: 'autodate'
	}
];

function exists(app, name) {
	try {
		app.findCollectionByNameOrId(name);
		return true;
	} catch {
		return false;
	}
}

migrate(
	(app) => {
		if (!exists(app, 'tournaments')) {
			const c = 'tournaments';
			app.save(
				new Collection({
					createRule: null,
					deleteRule: null,
					updateRule: null,
					listRule: `status != "draft" || ${STAFF}`,
					viewRule: `status != "draft" || ${STAFF}`,
					name: c,
					type: 'base',
					indexes: [
						'CREATE UNIQUE INDEX `idx_tournaments_slug` ON `tournaments` (`slug`)',
						'CREATE INDEX `idx_tournaments_status` ON `tournaments` (`status`, `startsAt`)'
					],
					fields: [
						id(c),
						text(c, 'name', 120, true),
						text(c, 'slug', 140, true),
						text(c, 'description', 5000),
						text(c, 'rules', 5000),
						select(c, 'format', ['single_elim', 'double_elim', 'round_robin']),
						number(c, 'bestOf', true),
						number(c, 'finalsBestOf'),
						bool(c, 'grandFinalReset'),
						select(c, 'status', [
							'draft',
							'registration',
							'seeding',
							'in_progress',
							'completed',
							'cancelled'
						]),
						date(c, 'registrationClosesAt'),
						date(c, 'startsAt'),
						number(c, 'maxParticipants'),
						json(c, 'mapPool'),
						image(c, 'banner', 5 * 1024 * 1024, ['1200x300']),
						image(c, 'logo', 2 * 1024 * 1024, ['128x128']),
						relation(c, 'createdBy', '_pb_users_auth_'),
						...autodates(c)
					]
				})
			);
		}

		const tournaments = app.findCollectionByNameOrId('tournaments');
		const visible = `tournament.status != "draft" || ${STAFF}`;

		if (!exists(app, 'tournament_participants')) {
			const c = 'tournament_participants';
			app.save(
				new Collection({
					createRule: null,
					deleteRule: null,
					updateRule: null,
					listRule: visible,
					viewRule: visible,
					name: c,
					type: 'base',
					indexes: [
						'CREATE UNIQUE INDEX `idx_tournament_participants_user` ON `tournament_participants` (`tournament`, `user`)',
						'CREATE INDEX `idx_tournament_participants_steam` ON `tournament_participants` (`steamId`)'
					],
					fields: [
						id(c),
						relation(c, 'tournament', tournaments.id, true, true),
						relation(c, 'user', '_pb_users_auth_', true, true),
						text(c, 'steamId', 20, true),
						number(c, 'profileId', true),
						text(c, 'alias', 120),
						text(c, 'country', 4),
						number(c, 'rating'),
						number(c, 'seed'),
						select(c, 'status', ['registered', 'withdrawn', 'disqualified']),
						number(c, 'placement'),
						...autodates(c)
					]
				})
			);
		}

		const participants = app.findCollectionByNameOrId('tournament_participants');

		if (!tournaments.fields.getByName('winner')) {
			tournaments.fields.add(new Field(relation('tournaments', 'winner', participants.id)));
			app.save(tournaments);
		}

		if (!exists(app, 'tournament_maps')) {
			const c = 'tournament_maps';
			app.save(
				new Collection({
					createRule: null,
					deleteRule: null,
					updateRule: null,
					listRule: '',
					viewRule: '',
					name: c,
					type: 'base',
					indexes: ['CREATE INDEX `idx_tournament_maps_name` ON `tournament_maps` (`name`)'],
					fields: [
						id(c),
						text(c, 'name', 80, true),
						image(c, 'icon', 2 * 1024 * 1024, ['256x256']),
						relation(c, 'createdBy', '_pb_users_auth_'),
						...autodates(c)
					]
				})
			);
		}

		if (!exists(app, 'tournament_matches')) {
			const c = 'tournament_matches';
			app.save(
				new Collection({
					createRule: null,
					deleteRule: null,
					updateRule: null,
					listRule: visible,
					viewRule: visible,
					name: c,
					type: 'base',
					indexes: [
						'CREATE INDEX `idx_tournament_matches_tournament` ON `tournament_matches` (`tournament`, `status`)',
						'CREATE INDEX `idx_tournament_matches_status` ON `tournament_matches` (`status`)'
					],
					fields: [
						id(c),
						relation(c, 'tournament', tournaments.id, true, true),
						select(c, 'bracket', ['winners', 'losers', 'grand_final', 'round_robin']),
						number(c, 'round', true),
						number(c, 'position'),
						number(c, 'bestOf', true),
						relation(c, 'playerA', participants.id),
						relation(c, 'playerB', participants.id),
						number(c, 'winsA'),
						number(c, 'winsB'),
						relation(c, 'winner', participants.id),
						select(c, 'status', ['pending', 'ready', 'completed']),
						date(c, 'readyAt'),
						text(c, 'nextMatch', 15),
						text(c, 'nextSlot', 1),
						text(c, 'loserNextMatch', 15),
						text(c, 'loserNextSlot', 1),
						json(c, 'games'),
						bool(c, 'manual'),
						bool(c, 'bye'),
						...autodates(c)
					]
				})
			);
		}
	},
	(app) => {
		try {
			app.delete(app.findCollectionByNameOrId('tournament_maps'));
		} catch {
			// already gone
		}

		try {
			app.delete(app.findCollectionByNameOrId('tournament_matches'));
		} catch {
			// already gone
		}

		try {
			const tournaments = app.findCollectionByNameOrId('tournaments');
			tournaments.fields.removeByName('winner');
			app.save(tournaments);
		} catch {
			// already gone
		}

		for (const name of ['tournament_participants', 'tournaments']) {
			try {
				app.delete(app.findCollectionByNameOrId(name));
			} catch {
				// already gone
			}
		}
	}
);
