import { app } from '$core/app';
import { generatePassword, generateUniqueId } from '$lib/utils/password';
import { Feature } from '../feature.svelte';

export type AuthSettings = {
	userId: string;
	email: string;
	password: string;
};

/**
 * Auth feature to handle user authentication with PocketBase.
 *
 * Enables automatic user creation and login.
 * Email, password, and userId are configurable and generated by default.
 *
 * @todo
 * Maybe in the feature make it possible to link an existing account?
 * Or have a way to let user input their own email/password?
 */
export class Auth extends Feature<AuthSettings> {
	name = 'auth';

	async enable() {
		await app.pocketbase
			.collection('users')
			.getOne(this.settings.userId)
			.then(() =>
				app.pocketbase
					.collection('users')
					.authWithPassword(this.settings.email, this.settings.password)
			)
			.catch(() =>
				app.pocketbase.collection('users').create({
					id: this.settings.userId,
					email: this.settings.email,
					password: this.settings.password,
					passwordConfirm: this.settings.password
				})
			)
			.catch((err) => {
				console.error(
					'Failed to authenticate or create user in Auth feature.',
					err,
					this.settings.userId,
					this.settings.email,
					this.settings.password
				);
			});
	}

	defaultSettings() {
		return {
			userId: generateUniqueId(),
			email: crypto.randomUUID() + '@fknoobs.com',
			password: generatePassword(),
			enabled: true
		};
	}
}

export const auth = new Auth();
