import { app } from '$core/app';
import type { UsersResponse } from '$core/pocketbase/types';
import { generatePassword, generateUniqueId } from '$lib/utils/password';
import { debounce, uniq } from 'lodash-es';
import { Feature } from '../feature.svelte';
import { watch } from 'runed';
import { fetch } from '@tauri-apps/plugin-http';

export type AuthSettings = {
	userId: string;
	email: string;
	password: string;
	enabled: boolean;
};

/**
 * Auth feature to handle user authentication with PocketBase.
 *
 * Enables automatic user creation and login.
 * Email, password, and userId are configurable and generated by default.
 *
 * @todo
 * Maybe in the feature make it possible to link an existing account?
 * Or have a way to let user input their own email/password?
 */
export class Auth extends Feature<AuthSettings> {
	name = 'auth';

	private _user: UsersResponse<string[]> | null = $state(null);

	async enable() {
		await app.pocketbase
			.collection('users')
			.getOne(this.settings.userId)
			.then(() =>
				app.pocketbase
					.collection('users')
					.authWithPassword(this.settings.email, this.settings.password)
					.then((auth) => auth.record)
			)
			.catch(() =>
				app.pocketbase.collection('users').create({
					id: this.settings.userId,
					email: this.settings.email,
					password: this.settings.password,
					passwordConfirm: this.settings.password
				})
			)
			.then((user) => {
				this._user = user as UsersResponse<string[]>;
			})
			.catch((err) => {
				console.error(
					'Failed to authenticate or create user in Auth feature.',
					err,
					this.settings.userId,
					this.settings.email,
					this.settings.password
				);
			});

		// TODO: Re-enable email update watcher when email change UI is added
		// $effect.root(() => {
		// 	watch(
		// 		() => this.settings.email,
		// 		(newEmail) =>
		// 			debounce(() => {
		// 				{
		// 					app.pocketbase
		// 						.collection('users')
		// 						.update(this.userId, { email: newEmail }, { fetch })
		// 						.then((updatedUser) => {
		// 							this._user = updatedUser as UsersResponse<string[]>;
		// 						});
		// 				}
		// 			}, 2000)
		// 	);
		// });
	}

	async refreshUser(): Promise<UsersResponse> {
		return app.pocketbase
			.collection('users')
			.getOne(this.settings.userId)
			.then((user) => {
				this._user = user as UsersResponse<string[]>;
				return this._user!;
			});
	}

	defaultSettings(): AuthSettings {
		return {
			userId: generateUniqueId(),
			email: crypto.randomUUID() + '@fknoobs.com',
			password: generatePassword(),
			enabled: true
		};
	}

	attachSteamId(steamId: string): Promise<UsersResponse> {
		if (!this.user) {
			throw new Error('No authenticated user to attach Steam ID to.');
		}

		return app.pocketbase
			.collection('users')
			.update(this.user.id, {
				steamIds: uniq([...(this.user.steamIds || []), steamId])
			})
			.then((updatedUser) => {
				this._user = updatedUser as UsersResponse<string[]>;
				return this._user;
			});
	}

	get user() {
		return {
			...this._user!,
			steamIds: this._user?.steamIds || []
		};
	}

	get userId() {
		return this.settings.userId;
	}

	get email() {
		return this.settings.email;
	}

	get password() {
		return this.settings.password;
	}

	get avatarUrl() {
		return app.pocketbase.files.getURL(this.user, this.user.avatar);
	}
}

export const auth = new Auth();
